### ISSUE TITLE
ReSharper Unity Support extension is incompatible with R# 2022.2.2

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#2354] opened 2022-09-03 20:46 UTC
Even though the extension can be installed from the menu, once Visual Studio is restarted, it is flagged as incompatible.

How can I get the Unity Support extension to work?

ReSharper 2022.2.20220820.133634
Unity Support 2022.2.0.143
Visual Studio 2022 (64-bit) Version 17.3.3

Thank you

**Comment by Fijit** [comment] 2022-09-04 18:33
I have the same issue as @aybe - same versions of R# and VS.

I wondered why namespaces were still being called out before noticing that the extension wasn't actually active due to incompatibility.

**Comment by tgoessler** [comment] 2022-09-05 07:17
The same for me.
Is there a new build planned for Resharper 2022.2.20220820.133634?

**Comment by AntiSilence** [comment] 2022-09-06 05:39
Having the same issue @citizenmatt 

![1](https://user-images.githubusercontent.com/1502419/188555164-e57ed957-ccbe-44ce-97e7-b1a3ba1ca440.png)

**Comment by citizenmatt** [comment] 2022-09-06 13:35
Sorry folks. I've been out of office and not able to look at this properly. There is an issue with 2022.2.2, and we're currently investigating. I expect we'll have something sorted very soon, in the next day or two. In the meantime, ReSharper 2022.2.1 will work with the Unity plugin.

The issue is related to the new extension API verifier. The idea is that we can load extensions built for older versions of ReSharper without having to recompile for each release, as long as the API is compatible. The installer will run the verifier over the extension at install/update time and if all is well, allow the extension to load. If there's a problem, the extension is marked as incompatible and blocked.

Unfortunately, the verifier doesn't handle the scenario of optional dependencies, and the Unity plugin has an optional dependency on ReSharper C++ for shader file support. Previously, the installer would show some warnings if ReSharper C++ was not installed, but everything would work at runtime, because ReSharper's component container sees that our shader support assembly requires a product feature that's not installed, and doesn't load any of those components. The API verifier doesn't have this information (it's a concept that's baked into the component container), and so the API verifier only sees an assembly in the extension that has unresolved dependencies on the types in ReSharper C++. This is easily worked around by installing ReSharper C++.

However, there's a problem with ReSharper 2022.2.2. The API verifier is marking the plugin as incompatible, even if ReSharper C++ is installed. Right now, I'm not sure what's going on, and I'm chatting to the developer in charge of the API verifier to see what's up. Hopefully we'll be able to quickly figure out what's wrong and fix it with a new build of the plugin.

Apologies again, and thanks for your patience.

**Comment by citizenmatt** [comment] 2022-09-06 14:35
Bad news, I'm afraid. We've figured out what's going wrong, and it's not something that we'll be able to fix solely in the plugin. It requires a change in both the plugin (#2346) and the API verifier, which we'll do for 2022.2.3, which is due in the next week or two. In the meantime, 2022.2.1 will continue to work. Apologies again.

**Comment by AntiSilence** [comment] 2022-09-06 16:48
Thank you for the update @citizenmatt 👍

**Closed** 2022-09-07 08:12 UTC

**Comment by aybe** [comment] 2022-09-07 13:21
Thank you!
