### ISSUE TITLE
Rider window doesn't get focus with double clicking script

### ISSUE THREAD

**Issue by mnarimani** [JetBrains/resharper-unity#1100] opened 2019-03-24 14:13 UTC
I'm on Windows 10. Using Unity 2018.3.7 and Rider JetBrains Rider 2018.3.3.
If I switch to Unity window without minimizing Rider, Everything works fine (I can double click on script and rider will pop up). 
But when I minimize Rider, it doesn't get opened anymore.

I tried enabling Verbose logging. But nothing showed up on the unity console window.

**Comment by van800** [comment] 2019-03-24 18:23
We haven't changed anything in this code recently
https://github.com/JetBrains/resharper-unity/blob/191/unity/EditorPlugin/OnOpenAssetHandler.cs#L158
You may try to play with it and submit a PR or I will look into it in 19.2 scope.

**Comment by sorencoder** [comment] 2019-03-26 11:11
I installed Rider 2019.1 EAP 2 and the double clicking issue seems to be solved. Rider gets focus and pops up whether it's minimized or not.

However there is another problem, Unity doesn't open Rider if it's not already open. 
I tested it with Rider 2018.3.3 and 2019.1 EAP 2 and both had this problem. I have to open Rider manually and load the solution. 

It would be nice if someone else could try to reproduce the problem. I don't know if it's Rider's problem or there is something on my machine that prevents Rider from starting.

**Comment by van800** [comment] 2019-03-26 11:16
Once the project has `Assets/Plugins/Editor/JetBrains/JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll`
opening Rider from Unity is expected to work. Could you check, if you have it?

**Comment by sorencoder** [comment] 2019-03-26 11:20
Yes I have the dll in that path.

**Comment by van800** [comment] 2019-03-26 11:29
Next thing to check is if Rider is selected as an external editor in Unity.
![image](https://user-images.githubusercontent.com/1482681/54993684-b88cdd80-4fc2-11e9-89ee-98a3bc76b6ad.png)

**Comment by sorencoder** [comment] 2019-03-26 11:39
Yes
![external tools](https://user-images.githubusercontent.com/30625116/54994240-6c9d6100-4fe1-11e9-9280-c6e2578eb712.png)
![rider](https://user-images.githubusercontent.com/30625116/54994248-7030e800-4fe1-11e9-9af8-9623bf180159.png)

**Comment by sorencoder** [comment] 2019-03-26 11:47
I think it's a problem with my machine. I tested it with someone else's machine and I couldn't reproduce the problem. I will try to reinstall stuff to make it work. 

Since the original problem is solved in Rider 2019.1 EAP 2, I'm closing this issue.

Thanks.

**Comment by van800** [comment] 2019-03-26 12:32
I tried it at my machine and it worked. 
We can investigate it further, if needed.
When you enable LogLevel =Verbose in Unity-Rider tab, you will start seeing a message in Unity Console. Something like: ` Logs path: C:\Temp\Unity3dRider\2019-03-26T-13-25-34.log.`
We are logging starting Rider by double click script in Unity like: 
`JetBrains.Rider.Unity.Editor.OnOpenAssetHandler | :1                             | "C:\Program Files\JetBrains\JetBrains Rider 191.6349.96\bin\rider64.exe" "F:\RiderProjects\pong-tdd\pong-tdd.sln" --line -1 "F:\RiderProjects\pong-tdd\Assets\MonoBehaviour1.cs"`

**Comment by sorencoder** [comment] 2019-07-08 16:09
I'm seeing this issue in 2019.2 EAP 2
I know it's hard to trace. This bug isn't even consistent on my own machine. But it's so annoying that can't be neglected.
Here I attach my log files:
[2019-07-08T-20-28-36.log](https://github.com/JetBrains/resharper-unity/files/3369249/2019-07-08T-20-28-36.log)
[2019-07-08T-20-31-27.log](https://github.com/JetBrains/resharper-unity/files/3369250/2019-07-08T-20-31-27.log)
I hope you can find something out of these log files.
Thanks!

**Comment by Baste-RainGames** [comment] 2019-07-10 06:22
Double-clicking scripts in Unity and having them open in Rider always works when you start editing. It will always stop working _at some point_. That point could be after a few minutes, it could be after hours. This has always been the case.

This bug's annoying, but also really hard to report properly. I'll try to look harder for if anything happens in the Rider console, but it's hard to spot when this issue hits. Is there any way we can get logs from what's supposed to be happening when we try to open a script from Unity?

**Comment by sorencoder** [comment] 2019-07-10 07:31
I have new info. 
If I have two instance of Unity and Rider open, And minimize Rider for Unity instance A, when I click on a script in Unity instance A, the Rider instance of Unity B gets the focus.
I hope it's useful. @van800

**Comment by SugoiDev** [comment] 2019-07-10 07:32
I can confirm this as well. As far as I know, there's no message anywhere. It's really  more of a Windows annoyance.
Here's a previous discussion from 2017: #252

The gist is that ensuring that a Window is the topmost one is a hard problem on Windows.
The only library that I know of that can consistently force that is AutoHotkey and the [solution is pretty complex](https://github.com/AutoHotkey/AutoHotkey/blob/4b8aa248906771a3e25744683dd161ef53c7555a/Source/window.cpp#L136)

**Comment by sorencoder** [comment] 2019-07-20 12:05
Any news on this? 
We are developing an online game and we always have two instances of Unity open.
This issue prevents us from using rider.

**Comment by van800** [comment] 2019-07-22 07:36
@sorencoder I tried your case with 2 instances, but it worked as expected.
Could you please try to do some external source debug?
1. Attach debugger to Unity
2. In Rider press Shift-Shift for GotoEverything. Search for `OnOpenAssetHandler`
![image](https://user-images.githubusercontent.com/1482681/61614372-d5c97400-ac63-11e9-8264-d215708a7739.png)
3. Find `ActivateWindow` and put brakepoint inside.
If `processId ` is null for some reason it can activate not the correct Rider window.

**Comment by sorencoder** [comment] 2019-07-22 18:48
@van800 I couldn't find OnOpenAssetHandler since I have precompiled dll of the plugin. I tried to copy paste the source code but it gave me errors. 
If you could give me instructions on how to use the source code it'd be awesome.

**Comment by van800** [comment] 2019-07-23 08:25
@sorencoder Could it be the case that you have Solution B folder inside Solution A? Or those folders are in completely different folders?

**Comment by sorencoder** [comment] 2019-07-23 09:09
@van800 There are in separate folders.
First Project Path: E:\projects\unity\RiderProject1\RiderProject1.sln`
Second Project Path: `E:\projects\unity\RiderProject2\RiderProject2.sln`

**Comment by van800** [comment] 2019-07-23 11:23
I would be glad to give you step by step instructions to debug. What Rider version do you use now? 2019.1.3 or 2019.2EAP4?

**Comment by sorencoder** [comment] 2019-07-23 16:55
I'm using Unity 2019.1.9f1 with this rider version:
```
JetBrains Rider 2019.2 EAP
Build #RD-192.5308.1339, built on July 17, 2019
Rider EAP User
Expiration date: August 16, 2019
Runtime version: 11.0.3+12-b304.19 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by van800** [comment] 2019-07-24 09:58
@sorencoder 
https://youtu.be/wGl3huYZRUM
Make sure that "Enable extenal source debug" setting is checked.
![image](https://user-images.githubusercontent.com/1482681/61784608-4f9b6200-ae0a-11e9-8913-ceeea62ce3ce.png)

**Comment by sorencoder** [comment] 2019-07-24 11:14
@van800 Is this normal that `num` is zero?
![image](https://user-images.githubusercontent.com/30625116/61789395-dca1e380-ae29-11e9-9cb8-90f4721af638.png)

**Comment by sorencoder** [comment] 2019-07-24 11:24
In log files I found an instance where `num` was zero. But somehow the process id doesn't match with process id in picture above.
```
15:49:50.347 |V| JetBrains.Rider.Unity.Editor.OnOpenAssetHandler | :1                             | ModifiedSource: False EditorApplication.isPlaying: False EditorPrefsWrapper.AutoRefresh: True
15:49:50.354 |V| JetBrains.Rider.Unity.Editor.OnOpenAssetHandler | :1                             | "C:\Users\Mohamad\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\192.5308.1339\bin\rider64.exe" "C:\Dev\Unity\ShipClient\ShipClient.sln" --line -1 "C:\Dev\Unity\ShipClient\Assets\Scripts\UIActivator.cs"
15:49:50.377 |V| JetBrains.Rider.Unity.Editor.OnOpenAssetHandler | :1                             | ActivateWindow: 4088 0
```

**Comment by van800** [comment] 2019-07-24 13:10
There are 2 different ways of opening editor and setting caret.
When Rider is not yet started, which is the case in the log, which you have attached, we are starting Rider and passing some commandline paramameters to it.
When Rider is already working and there is protocol connection between Rider and Unity, then we call `OpenFileLineCol`.
I also have seen debugger at the return statement, but this feels more like debugger issue with external sources, since there is no corresponding log messages.

My initial idea was to check if processId parameter of ActivateWindow call is null or not. Could you please check it in the debugger?

**Comment by sorencoder** [comment] 2019-07-24 14:16
processId always has value.

**Comment by sorencoder** [comment] 2019-07-24 14:18
Have you tried calling `ShowWindow` before `SetForegroundWindow`? 
https://stackoverflow.com/questions/27449298/setforegroundwindow-doesnt-work-with-minimized-process

**Comment by van800** [comment] 2019-07-24 20:10
I have tried that 
https://github.com/JetBrains/resharper-unity/blob/192/unity/EditorPlugin/OnOpenAssetHandler.cs#L160
but it is commented because it worked even without it.

I can make a build for you with it enabled (just to test) or you can compile the whole plugin locally and run with SDK, if you are curious.

**Comment by van800** [comment] 2019-07-26 13:42
@sorencoder please try this build https://drive.google.com/file/d/1t1yfdWYgTu7Ex9aoUf8UwdWmFG_B7Fe5/

**Comment by sorencoder** [comment] 2019-07-26 16:39
This almost fixed the issue. 
But there's a weird problem. When Rider is minimized, I have to click twice until the Rider opens up. On the first click it just makes the Rider icon blink in the taskbar. On the second click Rider pops up from minimized state.

**Comment by mnarimani** [comment] 2019-07-30 11:09
@van800 Take a look at this video:
https://youtu.be/sykcXSnVl04

Notice that on 00:16 the wrong rider instance gets the focus and with the second double click on 00:19 the correct instance pops up.

**Comment by van800** [comment] 2019-07-31 08:06
Thanks! I have reproduced the issue when Rider is minimized, and I will send you a new build with fix, once it compiles in my branch on CI.

**Closed** 2019-08-02 10:21 UTC

**Comment by mnarimani** [comment] 2019-08-02 10:42
@van800 @krasnotsvetov Thank you for your awesome work.
Do you have an ETA on the release of this fix?

**Comment by van800** [comment] 2019-08-02 11:28
@mnarimani Should we out with next EAP.
In the meantime, could you please check a private build, which I completely forgot to send you https://drive.google.com/file/d/1R_cE05r14ceZIxPvC-WZqxhxmxQVf5wS/

**Comment by mnarimani** [comment] 2019-08-02 12:08
Wow. It works like magic!
