### ISSUE TITLE
ShaderLab syntax error in Header attributes with names containing '(' and/or ')'

### ISSUE THREAD

**Issue by dimatomp** [JetBrains/resharper-unity#222] opened 2017-08-31 17:37 UTC
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Shaders/Obsolete/BlinnPhongConfigurable.shader
A syntax error is displayed for lines like `[Header(Base(RGB))]`, telling about expected ')' instead of '('. Unity allows using brackets in header names.

**Comment by citizenmatt** [comment] 2017-08-31 18:13
Duplicate of #187 

This has been fixed, and will be part of Rider 2017.2. Are you using Rider or ReSharper?

Also, thanks for the new test cases! :smile:

**Comment by citizenmatt** [comment] 2017-08-31 18:14
This has been fixed, and will be part of Rider 2017.2. Are you using Rider or ReSharper?

Also, thanks for the new test cases! :smile:

**Closed by citizenmatt** 2017-08-31 18:13 UTC

**Comment by dimatomp** [comment] 2017-08-31 18:16
I'm using ReSharper, sorry for duplicate.

**Comment by citizenmatt** [comment] 2017-08-31 18:20
No worries. I'm not too sure on the schedule for updating the ReSharper plugin, but I think it might be a nice idea to publish a new ReSharper version when we publish a new Rider version, which will be with the next Ride EAP. I'll try and get a new version out soon, though.
