### ISSUE TITLE
"Could not evaluate the value" when debugging with Unity (affects both 2018.1 release and nightly) with Unity 2018.2.0b1

### ISSUE THREAD

**Issue by SugoiDev** [JetBrains/resharper-unity#538] opened 2018-04-24 13:27 UTC
I did not test with older Unity versions.
Hovering any value when a breakpoint is hit shows the "{} Could not evaluate the value" message (see screenshot below).
![screenshot 2018 04 24-10 04 37](https://user-images.githubusercontent.com/7355630/39189829-96ea7e52-47a9-11e8-8970-551e7992b07b.png)

Immediately the exceptions in the attached log is thrown.
I tested both with alexzzzz's compiler and with the new Incremental Compiler. I was under the impression that the new incremental compiler could have been the cause, but it was not.
[log.txt](https://github.com/JetBrains/resharper-unity/files/1942903/log.txt)

I could not reproduce in an empty project.
Any pointers to get better data would be appreciated.

**Comment by van800** [comment] 2018-04-24 13:32
It would help, if you add Rider debugger logs, which can be found via Help->Show log in Explorer. There would be "DebuggerWorker" folder. Zip it and attach, thank you!

**Comment by van800** [comment] 2018-04-24 13:33
Such issue is more Rider one than the resharper-unity plugin one, but I think it is ok, to leave it here.

**Comment by van800** [comment] 2018-04-24 13:57
Ah, now I see we are aware about this problem. No need to attach logs.
The reason is new mono runtime in 2018.2.0b1.
We are working on it.

**Comment by van800** [comment] 2018-05-01 18:35
Confirmed that this is fixed in the nighly build.

**Closed by van800** 2018-05-01 18:35 UTC
