### ISSUE TITLE
Selecting rider as the external editor changes to vs-code

### ISSUE THREAD

**Issue by BLaZeKiLL** [JetBrains/resharper-unity#2422] opened 2023-10-01 21:29 UTC
I am trying to set rider as my external editor, but the drop-down changes to vs-code, and I also get a warning in Rider that advance unity integration is not enabled.

Specs
Unity - 2022.3.10f1
Rider - 2023.2.2
RiderFor unity - 3.0.25
OS - MacOS 14.0.2
Apple M1 Mac book Pro

https://github.com/JetBrains/resharper-unity/assets/33104478/08be74b1-0214-49bd-8a6a-be34f683aae5

**Comment by van800** [comment] 2023-10-02 08:02
Thank you for reporting. I have reproduced and I hope to have a fix shortly. 
For me it shows `JetBrains Rider (internal)` and doesn't switch to vscode.
In the meantime please fallback to the Rider package 3.0.24.

**Comment by BLaZeKiLL** [comment] 2023-10-02 08:53
Falling back to 3.0.24 didn't fix it, I updated to MacOS 14 a few days ago, but I am not fully certain if that broke it. I tried clearing the package cache also.

Rider is installed on my system using the toolbox app.

**Comment by van800** [comment] 2023-10-02 09:37
Remove the vscode package temporary, restart Unity. I guess it should help.

**Comment by van800** [comment] 2023-10-03 07:44
To try the new version, you may update manifest.json, substitute

`"com.unity.ide.rider": "3.0.25",`
by
`"com.unity.ide.rider": "https://github.com/van800/com.unity.ide.rider.git?path=/Packages/com.unity.ide.rider#3.0.26",`

Would it help? I want to start the release process asap, however it would help a lot, if you confirm that it helps in your case.

**Comment by BLaZeKiLL** [comment] 2023-10-03 10:10
Doesn't seem to fix it.

For now, I removed this from my packages
```
"com.unity.ide.visualstudio": "2.0.21",
```
With this, both 3.0.25 and 3.0.26 work fine

**Comment by van800** [comment] 2023-10-17 11:14
Closing this, because 3.0.26 was officially released.

**Closed by van800** 2023-10-17 11:14 UTC
