### ISSUE TITLE
Struct initialisation errors

### ISSUE THREAD

**Issue by vertxxyz** [JetBrains/resharper-unity#1320] opened 2019-09-19 07:57 UTC
> error CS0843: Auto-implemented property 'Test.Value' must be fully assigned before control is returned to the caller.

```
public struct Test {
	public bool ReadonlyValue { get; }
	public bool Value { get; set; }
	public Test(bool setValue) => ReadonlyValue = setValue;
}
```

This error seems to have no counterpart in Rider (2019.2), and yet Unity is determined it's a problem. This also means that CS0188 and CS0171 are also problematic.

Is there a way to tell Rider to recognise these as problematic, or for Unity to think they're not?

**Comment by van800** [comment] 2019-09-19 08:33
This error appears also in normal dotnet ClassLibrary, when you compile it in Rider or using commandline msbuild. Rider/Re# just don't have static analysis to spot such error without compilation.
I am closing this issue, since we can do nothing about it in the plugin scope.
Here is a new request for Re# team to implement analysis for such problem.
https://youtrack.jetbrains.com/issue/RSRP-476362

**Closed by van800** 2019-09-19 08:33 UTC

**Comment by citizenmatt** [comment] 2019-09-19 08:36
Looks like this is a bug in how the expression bodied constructor is handled. If it's converted to a normal constructor, the issue is correctly highlighted.
