### ISSUE TITLE
Is there any hotkey to quikly jump to documentation url

### ISSUE THREAD

**Issue by nicloay** [JetBrains/resharper-unity#300] opened 2017-12-05 18:20 UTC
In mono develop you can focus on any method and click Command+' and it will open browser with unity documentation

**Comment by IvanPashchenko** [comment] 2017-12-06 13:40
There's an inline documentation hotkey (Cmd-Q), but navigation to external docs is not implemented yet.

**Comment by citizenmatt** [comment] 2017-12-06 23:59
Duplicate of #98

**Closed by citizenmatt** 2017-12-06 23:59 UTC
Labels: enhancement
