### ISSUE TITLE
Rider launches wrong version of Unity after project upgrade

### ISSUE THREAD

**Issue by Kylotan** [JetBrains/resharper-unity#1507] opened 2020-02-04 14:21 UTC
We recently upgraded our Unity project from 2019.2.1f1 to 2019.3.0f6. The 'Start Unity' menu items on the 'Important Unity-related actions' didn't update to show the new versions until a restart, and now it shows the correct values. However, it doesn't seem to launch the right executable.

Menu:
![image](https://user-images.githubusercontent.com/1117104/73752488-f87f2e00-4758-11ea-88cd-a217bc254e04.png)

Unity, when I click the top menu item:
![image](https://user-images.githubusercontent.com/1117104/73752810-81966500-4759-11ea-9c45-d81c6fc17336.png)

Windows 10
JetBrains Rider 2019.3.1
Build #RD-193.5662.14, built on December 19, 2019

**Comment by van800** [comment] 2020-02-04 20:55
As a workaround, remove csproj files, start Unity would regenerate them. Problem would be solved.

However the issue is clear, I will look into it.

**Comment by van800** [comment] 2020-03-29 08:25
fixed by https://github.com/JetBrains/resharper-unity/pull/1572
Should be available in EAP6.

**Closed by van800** 2020-03-29 08:25 UTC
