### ISSUE TITLE
Please add an option to hide or customize the Unity gutter icon

### ISSUE THREAD

**Issue by hesselmonk** [JetBrains/resharper-unity#327] opened 2018-01-12 08:46 UTC
It is a minor issue, but the current design for the gutter icon is extremely distracting to me. I'd love to be able to turn it off or use a much more muted version of the icon.

**Comment by citizenmatt** [comment] 2018-01-12 09:02
We hoping to address this as part of 2018.1

Duplicate of #94

**Closed by citizenmatt** 2018-01-12 09:02 UTC
