### ISSUE TITLE
`Copying assembly from 'Temp/Assembly-CSharp.dll' to 'Library/ScriptAssemblies/Assembly-CSharp.dll' failed` when attached to Unity

### ISSUE THREAD

**Issue by oxysoft** [JetBrains/resharper-unity#964] opened 2018-12-15 06:01 UTC
Unity fails to compile changes with this error when Rider is attached to Unity for debugging.

`Copying assembly from 'Temp/Assembly-CSharp.dll' to 'Library/ScriptAssemblies/Assembly-CSharp.dll`

Unity 2018.3.0f2 with the `IncrementalCompiler 0.0.042-preview.31` package installed.

```
JetBrains Rider 2018.3 EAP
Build #RD-183.5047.25, built on December 14, 2018
Rider EAP User
Expiration date: January 13, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by ManHunterGroms** [comment] 2018-12-18 18:54
Same problem.
Help disable debug mode and recompile scripts.

**Comment by van800** [comment] 2018-12-19 08:11
https://youtrack.jetbrains.com/issue/RIDER-22770

**Comment by van800** [comment] 2018-12-19 10:42
Does it reproduce without IC, which is deprecated btw.
I tried to reproduce, but no luck for now.

**Comment by van800** [comment] 2018-12-19 11:15
@oxysoft if possible, please share your manifest.json

**Comment by aaronhoogstraten** [comment] 2018-12-20 00:12
I am experiencing this with Unity 5.6.3p3

**Comment by van800** [comment] 2018-12-20 08:36
Clear steps to reproduce with some simple project would help a lot.

**Comment by sebas77** [comment] 2018-12-20 09:51
I can repro it 100% of the times and I don't have IC package installed, how can I help?

**Comment by van800** [comment] 2018-12-20 10:07
@sebas77 
1. Please provide me with the repro-steps.
2. Please check which process holds handle to the file. (you may use one of the suggestions from here https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows)

**Comment by sebas77** [comment] 2018-12-20 10:08
Are you suggesting the step 2 just to be sure that it's rider to hold it? (Because I am pretty sure it is)

**Comment by sebas77** [comment] 2018-12-20 10:09
The manifest are very simple, now I will try the to find the minimum repro steps (it's pretty simple really). I can share my project too if you want.

[manifest.zip](https://github.com/JetBrains/resharper-unity/files/2698351/manifest.zip)

**Comment by sebas77** [comment] 2018-12-20 10:13
OK so:

open the project->attach the debugger->change the files->compiles and works normally
open the project->attach the debugger->open the test runner->run a test->hitting a breakpoint->finish debug session without detaching->change files->compiles and breaks.
Seems to be related to the unity test runner in my case. It works with the previous version of Rider of course.

**Comment by van800** [comment] 2018-12-20 10:50
Thanks for the repro. I was asking for step 2, because it may be Unity holding the file.

**Comment by sebas77** [comment] 2018-12-20 11:06
well I guess if it works with the previous Rider version it shouldn't be, right?

**Comment by van800** [comment] 2018-12-20 11:19
@sebas77 I reproduced it with your steps! I am passing it to debugger team.
![image](https://user-images.githubusercontent.com/1482681/50281952-79923d80-0451-11e9-908e-436b69ccc52c.png)

**Comment by sebas77** [comment] 2018-12-20 12:53
glad to help, waiting for the fix before to switch to the new version

**Comment by van800** [comment] 2018-12-26 12:44
Fixed in Rider 2018.3.1, which is going to be released in a couple of days.

**Closed by van800** 2018-12-26 12:44 UTC

**Comment by daschatten** [comment] 2019-01-23 14:42
@van800 I experience the same issue in Rider 2018.3.1 and Unity 2018.3.2

Steps:

1. Set a breakpoint somehwere
2. Attach debugger
3. Enter play mode
4. Hit breakpoint
5. Exit play mode
6. Change something in code
-> `Copying assembly from 'Temp/Assembly-CSharp.dll' to 'Library/ScriptAssemblies/Assembly-CSharp.dll' failed`

**Comment by van800** [comment] 2019-01-24 07:30
@daschatten Your OS? Thank you for the repro-steps.

**Comment by van800** [comment] 2019-01-24 12:17
@daschatten Doesn't reproduce for me on Windows. Btw, there is no possibility to do (5) Exit Play mode while being on a brakepoint. What step is missing there?

**Comment by daschatten** [comment] 2019-01-26 11:35
@van800 Step 4.5: Resume Program is missing
I'm on Win 10. Happens since Rider 2018.3 upgrade.

Also seeing follwing error six times in Unity console (Missed it before).

`ArgumentNullException: Value cannot be null.
Parameter name: source
System.Linq.Enumerable.Any[TSource] (System.Collections.Generic.IEnumerable`1[T] source) (at <1b13ba6391c74847bbc3eddc86df7eee>:0)
UnityEditor.RiderPathLocator+<CollectPathsFromToolbox>c__AnonStorey3.<>m__0 (System.String a) (at C:/buildslave/unity/build/Editor/Mono/SyncRiderProject.cs:198)
UnityEditor.SyncRiderProject:PathCallback()
UnityEditorInternal.ScriptEditorUtility:GetFoundScriptEditorPaths(RuntimePlatform) (at C:/buildslave/unity/build/Editor/Mono/ScriptEditorUtility.cs:146)
UnityEditor.SettingsWindow:OnEnable()`

**Comment by van800** [comment] 2019-01-26 12:04
Please see https://youtrack.jetbrains.com/issue/RIDER-23678

**Comment by daschatten** [comment] 2019-01-26 12:34
Thx, will wait for 2018.3.2 :-)

**Comment by van800** [comment] 2019-01-28 10:41
@daschatten issue `Copying assembly failed` doesn't reproduce for me. Could you please add a sample solution on which it does?
I assume you are on new mono runtime in Unity, right?
![image](https://user-images.githubusercontent.com/1482681/51831134-b1628f80-22f1-11e9-9f36-620016226320.png)

**Comment by daschatten** [comment] 2019-01-30 13:53
Hey @van800,

i just upgraded to Rider 2018.3.2 and problem is gone :-)

**Comment by van800** [comment] 2019-01-30 13:53
Thanks for letting us know.

**Comment by paulrayrussell** [comment] 2019-03-19 15:24
I'm still getting this problem in the latest Rider version.

**Comment by van800** [comment] 2019-03-19 15:37
@paulrayrussell Does it reproduce on any solution or only yours main one? By latest Rider version, do you mean 2019.1 EAP1? What is your Unity version and what scripting runtime in Unity is used? Please provide also "Steps to reproduce".

**Comment by paulrayrussell** [comment] 2019-03-19 18:11
Rider: RD183.6092.12. Unity 2018.3. .Net 3.5 Equivalent. I'll spend a few mins trying to reproduce tomorrow - but the problem is intermittent and I've not enough time. I've been discussing with Unity support: they've indicated to disable antivirus etc, which I've done. Everything was better was some days, but I noticed it started happening a lot today particularly and notably during a Rider debugging session. If I leave Rider running in debug mode whilst coming in and out of play in Editor. The problem happened maybe 4 times. Locks up Unity, completely with the OP's listed error. That, given my time constraints, I fear, may be as much as I can help here. But I'll try to watch out for the problem, given this new angle, over the coming days.

**Comment by van800** [comment] 2019-03-20 10:45
@paulrayrussell Unfortunately doesn't reproduce for me. 
For Windows, you may use Process Explorer to check which process is locking particular file https://www.mysysadmintips.com/windows/clients/593-find-what-is-locking-a-file-using-sysinternals-process-explorer
I never tried something similar on Mac, but it should be also possible.
