### ISSUE TITLE
[Feature Request] Visual Studio to trigger assembly reload like Rider does

### ISSUE THREAD

**Issue by aybe** [JetBrains/resharper-unity#1903] opened 2020-10-20 22:24 UTC
In Rider there's a pretty cool feature: whenever you save or rebuild the project, Unity starts reloading assemblies in background.

This is very useful when for instance you have your IDE on the left and Unity on the right, you don't have to focus Unity window solely for it to reload assemblies.

But Visual Studio doesn't exhibit such behavior.

Can we hope to get the same feature for Visual Studio one day?

**Comment by aybe** [comment] 2020-10-21 02:32
Well, contrarily to what I've said before, it appears that this feature is present but it's unclear as on how it works.
At some point I see that Unity progress ring spins as soon as I save code in VS, but not always, sometimes it's a pad lock.
So it started working but after something unknown I've probably done ... any guidance would be appreciated.

Thank you.

**Comment by van800** [comment] 2020-10-21 06:21
Duplicate of https://github.com/JetBrains/resharper-unity/issues/742

@aybe I am not aware, why it may sometimes work in VS, maybe it is VSTU implementation if the same feature?

**Closed by van800** 2020-10-21 06:21 UTC

**Comment by aybe** [comment] 2020-10-21 22:05
@van800 okay, I'll ask VSTU team and see what they say, thanks!
