### ISSUE TITLE
Debugger breaks when using GetBuffer/GetComponent inside Entities.ForEach loops

### ISSUE THREAD

**Issue by Sylmerria** [JetBrains/resharper-unity#2046] opened 2021-03-16 09:52 UTC
Using Rider 20.3.3 & lastest unity package for rider

Entities.ForEach loops allow now to bypass GetComponentDataFromEntity & GetBufferFromEntity call before the loop with a nicer API GetComponent & GetBuffer ( methods from SystemBase) directly callable inside the loop.

When using this methods, the debugger stops his progress in the current method and goes up of one level.
```
            Entities .ForEach((Entity entity) =>
                     {
                          var foo = 5;
                          //GetBuffer will break debugger 
                         var     bb                 = GetBuffer<buffer>(entity);
                         //debugger never break here
                         foo +=15;
                      })
                    .Schedule()
```

Also breakpoint after a GetComponent or GetBuffer call will never stops execution.
When it sets before however, it will.

**Comment by citizenmatt** [comment] 2021-03-18 08:42
Thanks for the report. Would it possible to provide a super simple repro project, please?

**Comment by Sylmerria** [comment] 2021-03-18 11:21
@citizenmatt  I have one very simple one, how do you want I share it with you ?

**Comment by citizenmatt** [comment] 2021-03-18 11:23
Great, thanks! Whatever's convenient to you - attach here, create a ticket at youtrack.jetbrains.com and attach there, email me at matt@jetbrains.com or throw it into a temp GitHub project. I don't mind, I'll grab it :)

**Comment by Sylmerria** [comment] 2021-03-18 12:39
I think breakpoints are conserved with the projet.

[riderDebugger.zip](https://github.com/JetBrains/resharper-unity/files/6164097/riderDebugger.zip)

**Comment by Sylmerria** [comment] 2021-03-19 11:06
@citizenmatt can you reproduce the bug with the sample or do you need more informations ?

**Comment by krasnotsvetov** [comment] 2021-04-05 15:12
@Sylmerria, thank you for repro. I have reproduced it with your sample and pass it to our debugger team. Also I created an issue in youtrack - https://youtrack.jetbrains.com/issue/RIDER-60806

Also, I have found workaround: 
Use `step into` at GetBuffer and after that use `step over` until you reach final bracket of method
![image](https://user-images.githubusercontent.com/15616242/113589069-9ad6c200-9639-11eb-9562-d9390f429d90.png)

At final bracket, press again `step into` and debugger will correctly return to code after `GetBuffer`.

**Comment by citizenmatt** [comment] 2021-09-03 08:16
Closing this ticket, as it's something that's been explored by the debugger team. More details at [RIDER-60806](https://youtrack.jetbrains.com/issue/RIDER-60806)

**Closed by citizenmatt** 2021-09-03 08:16 UTC

**Comment by Sylmerria** [comment] 2021-10-04 08:58
The rider ticket is closed without solution but @krasnotsvetov found a manual workaround. 
Is there a way to do that automaticaly ?

**Comment by kalibannez** [comment] 2022-06-30 15:29
Is there any progress? Problem still existing.

**Comment by citizenmatt** [comment] 2022-07-04 15:12
AIUI, this is due to Burst compiled code, which doesn't provide Rider with the correct debugging information. I believe the next version of Unity will disable Burst when under the debugger, which means these code blocks will start to work again.
