### ISSUE TITLE
Unity crashes while debugging using the latest version of Unity and Rider

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#1059] opened 2019-02-23 09:16 UTC
It used to crash very often, but since I disabled the editing while debugging, it happened just once in the last 24 hours:

Unity Editor by Unity Technologies [version: Unity 2018.3.6f1_a220877bc173]

Unknown caused an Access Violation (0xc0000005)
  in module Unknown at 0033:61509f20.

Error occurred at 2019-02-22_191158.
Unknown, run by smandala.

38% physical memory in use.
32719 MB physical memory [20145 MB free].
1549 MB process peak paging file [1140 MB used].
1144 MB process peak working set [957 MB used].
System Commit Total/Limit/Peak: 15206MB/34767MB/32799MB
System Physical Total/Available: 32719MB/20145MB
System Process Count: 212
System Thread Count: 3053
System Handle Count: 105352
Disk space data for 'C:\Users\smandala\AppData\Local\Temp\Unity\Editor\Crashes\Crash_2019-02-22_191123205\': 5035085824 bytes free of 127313387520 total.

Read from location 0000000000000040 caused an access violation.

Context:
RDI:    0x0000000078fd5eb0  RSI: 0x00000000789af540  RAX:   0x0000000000000000
RBX:    0x000000007ceaf750  RCX: 0x0000000000000000  RDX:   0x00000000789af540
RIP:    0x00007fff61509f20  RBP: 0x000000003facbb80  SegCs: 0x0000000000000033
EFlags: 0x0000000000010202  RSP: 0x000000007ceaf658  SegSs: 0x000000000000002b
R8:     0x000000007ceaf750  R9:  0x000000007ceaf860  R10:   0x0000000078997db0
R11:    0x000000007ceafa30  R12: 0x0000000000000000  R13:   0x000000007ceaf860
R14:    0x0000000000000130  R15: 0x0000000018d2cb10

Bytes at CS:EIP:
48 8b 41 40 c3 cc cc cc cc cc cc cc cc cc cc cc 

Mono DLL loaded successfully at 'E:\Unity\Hub\Editor\2018.3.6f1\Editor\Data\MonoBleedingEdge\EmbedRuntime\mono-2.0-bdwgc.dll'.

Stack Trace of Crashed Thread 2088:
0x00007FFF61509F20 (mono-2.0-bdwgc) mono_class_get_image
0x00007FFF61522923 (mono-2.0-bdwgc) mono_debug_symfile_lookup_method
0x00007FFF61579701 (mono-2.0-bdwgc) mono_set_config_dir
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFF614D1E7C)
0x00007FFF614D1E7C (mono-2.0-bdwgc) (function-name not available)
0x00007FFF6157A79E (mono-2.0-bdwgc) mono_debug_lookup_method
0x00007FFF616F2C08 (mono-2.0-bdwgc) mono_unity_backtrace_from_context
0x00007FFF616FE3CB (mono-2.0-bdwgc) mono_debugger_agent_transport_handshake
ERROR: SymGetSymFromAddr64, GetLastError: 'Attempt to access invalid address.' (Address: 00007FFF614D1E7C)
0x00007FFF614D1E7C (mono-2.0-bdwgc) (function-name not available)
0x00007FFF616FFB6C (mono-2.0-bdwgc) mono_debugger_agent_transport_handshake
0x00007FFF614FC30F (mono-2.0-bdwgc) mono_domain_foreach

deferred-', PDB: '', fileVersion: 10.0.17134.1

========== OUTPUTTING STACK TRACE ==================

0x00007FFF61522923 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\debug-mono-symfile.c:751] mono_debug_symfile_lookup_method 
0x00007FFF61579701 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\mono-debug.c:319] lookup_method_func 
0x00007FFF614D1E7C (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\eglib\ghashtable.c:354] monoeg_g_hash_table_foreach 
0x00007FFF6157A79E (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\mono-debug.c:353] mono_debug_lookup_method 
0x00007FFF616F2C08 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:3763] create_event_list 
0x00007FFF616FE3CB (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:4100] process_profiler_event 
0x00007FFF614D1E7C (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\eglib\ghashtable.c:354] monoeg_g_hash_table_foreach 
0x00007FFF616FFB6C (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:4369] send_types_for_domain 
0x00007FFF614FC30F (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\domain.c:980] mono_domain_foreach 
0x00007FFF616F6CD1 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:9214] event_commands 
0x00007FFF616F399E (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:12053] debugger_thread 
0x00007FFF615A5458 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\threads.c:1034] start_wrapper_internal 
0x00007FFF615A51E6 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\threads.c:1093] start_wrapper 
0x00007FFFDE303DC4 (KERNEL32) BaseThreadInitThunk
0x00007FFFE0ED3691 (ntdll) RtlUserThreadStart

========== END OF STACKTRACE ===========

A crash has been intercepted by the crash handler. For call stack and other details, see the latest crash report generated in:
 * C:/Users/smandala/AppData/Local/Temp/Unity/Editor/Crashes

All the crashes can be found here:
[Crashes.zip](https://github.com/JetBrains/resharper-unity/files/2896665/Crashes.zip)

**Comment by van800** [comment] 2019-02-23 09:39
Could you please add repro-steps?

**Comment by sebas77** [comment] 2019-02-23 09:42
Hello, unluckily I didn't get a way to reproduce it solidly. 

Most of the time is reproducible while debugging, but the very last one which I reported, happened on hot reload.

**Comment by joncham** [comment] 2019-02-23 15:40
There are a few different crashes I see.

1
=
**2018.3**

This one I am fairly sure is caused by the debugger getting events while a domain is unloaded. We have bug tracking this but it's not public ATM. I can adjust that.

0x00007FFF61522923 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\debug-mono-symfile.c:751] mono_debug_symfile_lookup_method
0x00007FFF61579701 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\mono-debug.c:319] lookup_method_func
0x00007FFF614D1E7C (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\eglib\ghashtable.c:354] monoeg_g_hash_table_foreach
0x00007FFF6157A79E (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\mono-debug.c:353] mono_debug_lookup_method
0x00007FFF616F2C08 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:3763] create_event_list
0x00007FFF616FE3CB (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:4100] process_profiler_event
0x00007FFF614D1E7C (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\eglib\ghashtable.c:354] monoeg_g_hash_table_foreach
0x00007FFF616FFB6C (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:4369] send_types_for_domain
0x00007FFF614FC30F (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\domain.c:980] mono_domain_foreach
0x00007FFF616F6CD1 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:9214] event_commands
0x00007FFF616F399E (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\mini\debugger-agent.c:12053] debugger_thread
0x00007FFF615A5458 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\threads.c:1034] start_wrapper_internal
0x00007FFF615A51E6 (mono-2.0-bdwgc) [c:\buildslave\mono\build\mono\metadata\threads.c:1093] start_wrapper

2
=
**2019.1**
This is a known issue and has been fixed: https://issuetracker.unity3d.com/issues/crash-on-clear-assembly-from-modifiers-when-entering-play-mode-from-rider-debug

0x00007FFFA0361E35 (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\mini\debugger-agent.c:8089] clear_assembly_from_modifiers 
0x00007FFFA03624A2 (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\mini\debugger-agent.c:8113] clear_event_requests_for_assembly 
0x00007FFFA0360C6E (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\mini\debugger-agent.c:4330] assembly_unload 
0x00007FFFA0206FC5 (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\metadata\profiler-events.h:71] mono_profiler_raise_assembly_unloading 
0x00007FFFA016F7EB (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\metadata\assembly.c:3855] mono_assembly_close_except_image_pools 
0x00007FFFA016C63E (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\metadata\domain.c:1138] mono_domain_free 
0x00007FFFA0169EEF (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\metadata\appdomain.c:2623] unload_thread_main 
0x00007FFFA0215558 (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\metadata\threads.c:1034] start_wrapper_internal 
0x00007FFFA02152E6 (mono-2.0-bdwgc) [c:\users\builduser\builds\1r5m1xkj\0\vm\mono\mono\metadata\threads.c:1093] start_wrapper 
0x00007FFFDE303DC4 (KERNEL32) BaseThreadInitThunk
0x00007FFFE0ED3691 (ntdll) RtlUserThreadStart

3
=
**2018.3**

This seems unrelated to debugger.

0x0000000140BF2A0D (Unity) Scripting::GetInstanceIDFor
0x0000000140C3AF54 (Unity) Transfer_UnityEngineObject<StreamedBinaryWrite,0>
0x0000000140BB6E91 (Unity) TransferScriptingObject<StreamedBinaryWrite>
0x0000000140BB42E1 (Unity) SerializableManagedRefTransfer::Transfer<SerializableManagedRefBackupGenerator>
0x0000000140C7870E (Unity) WriteObjectToVector
0x0000000140E4A787 (Unity) CachedPrefabPPtrRemapper::GetCachedPrefabSourceObjectData
0x0000000140E4386E (Unity) ApplyPrefabStateAndPropertyModificationsToObjects
0x0000000140E5032A (Unity) MergePrefabChanges
0x0000000140E50941 (Unity) MergePrefabInternal
0x0000000140E4DE48 (Unity) MergeAllPrefabInstancesDuringLoad
0x00000001409A869E (Unity) LoadSceneOperation::CompleteAwakeSequence
0x00000001409A9418 (Unity) LoadSceneOperation::IntegrateMainThread
0x00000001409ACCFF (Unity) PreloadManager::UpdatePreloadingSingleStep
0x00000001409AD5DA (Unity) PreloadManager::WaitForAllAsyncOperationsToComplete
0x0000000140E6E4FC (Unity) EditorSceneManager::RestoreSceneBackups
0x000000014132DC8A (Unity) PlayerLoopController::EnterPlayMode
0x0000000141339CB3 (Unity) PlayerLoopController::SetIsPlaying
0x000000014133CB92 (Unity) Application::TickTimer
0x000000014149878B (Unity) MainMessageLoop
0x000000014149A426 (Unity) WinMain
0x000000014247F7EA (Unity) __scrt_common_main_seh
0x00007FFFDE303DC4 (KERNEL32) BaseThreadInitThunk
0x00007FFFE0ED3691 (ntdll) RtlUserThreadStart

**Comment by sebas77** [comment] 2019-02-23 15:44
Thanks a lot Jon! I definitively saw unity crashing on hot reload (or whatever you call when it reloads the code and recompile the dlls) without debugging attached, but it happened once or twice. I don't know if the Rider plugin can be still involved in that case too.

**Comment by van800** [comment] 2019-02-23 17:27
https://twitter.com/jon_cham/status/1099330661490540545

**Comment by sebas77** [comment] 2019-02-25 13:04
[Crash_2019-02-25_121008708.zip](https://github.com/JetBrains/resharper-unity/files/2900631/Crash_2019-02-25_121008708.zip)

Another crash, hope it helps, but not sure it's related.

**Comment by van800** [comment] 2019-02-26 09:13
Related https://youtrack.jetbrains.com/issue/RIDER-24859

**Comment by van800** [comment] 2019-02-26 16:09
> [Crash_2019-02-25_121008708.zip](https://github.com/JetBrains/resharper-unity/files/2900631/Crash_2019-02-25_121008708.zip)
> 
> Another crash, hope it helps, but not sure it's related.

Similar to (3)

**Comment by sebas77** [comment] 2019-02-27 08:09
Have you got any lead? Do these dump help?

**Comment by sebas77** [comment] 2019-02-27 10:23
This one was very weird. I left Unity open over night (not sure if it matters) today I started to work, Rider was left open over night too, I just jumped between files in the solution explorer and while doing that, unity crashed, while I was away from it. I enabled procdump auto dumping, I included it in this report

[Crashes.zip](https://github.com/JetBrains/resharper-unity/files/2909734/Crashes.zip)

**Comment by van800** [comment] 2019-02-27 11:01
> This one was very weird. I left Unity open over night (not sure if it matters) today I started to work, Rider was left open over night too, I just jumped between files in the solution explorer and while doing that, unity crashed, while I was away from it. I enabled procdump auto dumping, I included it in this report
> 
> [Crashes.zip](https://github.com/JetBrains/resharper-unity/files/2909734/Crashes.zip)

This one is obviously caused by:
NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Behaviour.get_isActiveAndEnabled(UnityEngine.Behaviour)
  at UnityEngine.UI.Selectable.OnValidate () [0x00028] in C:\buildslave\unity\build\Extensions\guisystem\UnityEngine.UI\UI\Core\Selectable.cs:458 
  at TMPro.TMP_InputField.OnValidate () [0x00001] in E:\Boxtopia-Mainline\Library\PackageCache\com.unity.textmeshpro@1.3.0\Scripts\Runtime\TMP_InputField.cs:732

**Comment by sebas77** [comment] 2019-02-27 11:25
hmm weird, I am pretty sure I wasn't interacting with Unity when it crashed. Thanks for letting me know.

**Comment by van800** [comment] 2019-02-27 13:13
@sebas77 
I looked over the submitted crashes again and I think non of them are ours.
If you see JetBrains in the stacktrace is is likely us, otherwise - Unity.
Of course, if Unity support is pointing at us, then its likely us.
I am closing this issue for now, but feel free to add crashes to it.

**Closed by van800** 2019-02-27 13:13 UTC

**Comment by sebas77** [comment] 2019-03-05 17:59
Hello again,

it's a 100% repro, but now I know it happens often when I attach the debugger and click on play before unity finishes to compile/reload the dll. I now avoid this pattern, but when I forget it, it's almost always a crash.

**Comment by van800** [comment] 2019-03-12 14:42
@sebas77 this is something, which you need to submit to Unity support, we can't do almost anything about it.
