### ISSUE TITLE
2018.1 - Unused public method names in MonoBehavious are now dimmed - BUG

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#539] opened 2018-04-25 02:43 UTC
Hello,

Since upgrading to R# 2018.1 and Unity Support 2018.1.0.75,  I noticed that unused public method names are getting dimmed , which was NOT the case in previous version.
In Unity, public methods on MonoBehaviour are also used to bind UI events and therefore, they will have no reference in code. Prior to this update, the Unity Resharper plugin suppressed the dimming effect, but now it seems be broken 
Public methods on MonoBehavious should not be dimmed, regardless if they are being used or not. This causes unnecessary bloat to the source code with "unused method" warnings all over the place.

R# 2018.1
Unity Support 2018.1.0.75
Visual Studio 2017 15.6.6

Thanks,

![image](https://user-images.githubusercontent.com/1551002/39224355-96a6877a-480c-11e8-914d-fa48e898019f.png)

**Comment by rob8861** [comment] 2018-05-01 02:08
I noticed that someone already reported a similar issue  #488 but for Rider, so not sure if #539 should be treated as a duplicate or not. I'll let you guys decide.

**Comment by citizenmatt** [comment] 2018-05-01 08:30
Duplicate of #488

**Comment by citizenmatt** [comment] 2018-05-01 08:37
Yep, this is a duplicate. Unused public methods were previously only highlighted if you enabled [Solution Wide Error Analysis](https://www.jetbrains.com/help/rider/Code_Analysis__Solution-Wide_Analysis.html). Rider 2018.1 now calculates this by default, without having to enable the full analysis.

Rider doesn't know that these methods are being used by Unity, so marks them as unused. Marking them as used will require parsing Unity's project files, as YAML.

**Closed by citizenmatt** 2018-05-01 08:37 UTC

**Comment by rob8861** [comment] 2018-05-01 14:07
I am a Resharper user, so I don't know anything about Rider. 
All I know is that in Resharper 2017.3.x this wasn't an issue but something was changed in 2018.1.
I don't use Solution Wide Analysis to conserve resources, so I am not sure how that would affect how Resharper analyzes the project,

Suggestion: Instead of parsing Unity's YAML files ,which may result in some unwanted performance degradation, why not suppress all unused members warnings on all public methods in classes which inherit from one of Unity's base classes (MonoBehavior, NetworkBehavior, ScriptableObject etc).
