### ISSUE TITLE
Cannot find 'Unity Support' in Extension Manager

### ISSUE THREAD

**Issue by CTuckerCampbell** [JetBrains/resharper-unity#977] opened 2018-12-26 17:46 UTC
I am trying to find the Extension that adds support for Unity C# code, but can not find anything related to Unity in the Extension Manager window.  Do I need to install an earlier version of ReSharper or something?

**Comment by citizenmatt** [comment] 2018-12-27 13:57
Duplicate of #853

**Closed by citizenmatt** 2018-12-27 13:57 UTC
