### ISSUE TITLE
Missing in ReSharper´s Extension Manager

### ISSUE THREAD

**Issue by spixy** [JetBrains/resharper-unity#754] opened 2018-09-01 15:26 UTC
> The ReSharper plugin is installed via the ReSharper → Extension Manager. Simply search for "Unity Support".

It is missing there now (Resharper 2018.2.1)

![bug](https://user-images.githubusercontent.com/4542110/44947355-58f39880-ae0c-11e8-8917-1c992570461d.jpg)

**Comment by citizenmatt** [comment] 2018-09-03 08:14
Duplicate of #706

**Comment by citizenmatt** [comment] 2018-09-03 08:14
Sorry, the ReSharper 2018.2 release has taken a little longer than expected. It should be available later today.

**Closed by citizenmatt** 2018-09-03 08:14 UTC
