### ISSUE TITLE
Asmdef autocompletion is broken in v2019.1.0.78

### ISSUE THREAD

**Issue by xahon** [JetBrains/resharper-unity#1165] opened 2019-05-04 02:19 UTC
I noticed that `.asmdef` files is not highlighted in rider 2019.1.1 however I could edit it with autocompletion and syntax highlighting in rider 2018 with unity plugin v2018.*.*

**Comment by citizenmatt** [comment] 2019-05-06 10:22
Sadly, `.asmdef` support has broken in 2019.1, and was spotted too late to add mitigations for in the release. The problem is a technical one. 

Rider is built on top of IntelliJ and ReSharper. The ReSharper "backend" runs the C# analysis, while the IntelliJ "frontend" provides the user interface, plugins such as source control, and other file analysis and navigation. Rider uses IntelliJ for web technologies - HTML, CSS, JavaScript and JSON. But ReSharper also has support for those technologies, and the `.asmdef` support is based on ReSharper's JSON functionality. Unfortunately, Rider 2019.1 has completely disabled ReSharper's web technologies, including JSON, and that means `.asmdef` is no longer supported.

I'm intending to add some mitigations for 2019.1.2 (syntax highlighting and schema validation), with full support (completion and analysis of assembly names, dependencies and references) returned in 2019.2.

**Comment by Baste-RainGames** [comment] 2019-05-15 09:35
Could we as a temporary measure get a fix where Rider doesn't try to do anything special with .asmdef files? Right now hitting tab with an asmdef file open causes Rider to throw an exception 100% of the time. 

Or is that a different issue?

**Comment by citizenmatt** [comment] 2019-05-15 16:31
I'm not aware of any exceptions - do you have any examples, and a repro?

**Comment by Baste-RainGames** [comment] 2019-07-03 07:26
Yes I do! Sorry about the late reply, forgot about this.

As far as I can tell, trying to indent by hitting tab in any asmdef file, no matter the project, causes an exception. 

A repro that I just did is:
- Create empty Unity project (2018.4.2f1)
- Create Assets/Scripts/Assembly.asmdef and Assets/Scripts/Script.cs 
- Open project in Rider
- Open Assembly.asmdef
- Put your caret anywhere and press Tab:
- com.jetbrains.rdclient.util.BackendException: Object reference not set to an instance of an object.

I'm getting "This exception has already been reported as DEXP-461730", but the link I get for that seems to be broken.

**Comment by Baste-RainGames** [comment] 2019-08-01 14:14
Update: The issue I complained about above has been fixed in 2019.2 EAP 5, if not before.

**Closed** 2019-08-02 07:26 UTC
