### ISSUE TITLE
Github UPM Packages does not get loaded correctly

### ISSUE THREAD

**Issue by Podden** [JetBrains/resharper-unity#1838] opened 2020-09-10 10:35 UTC
My own packages hosted on github do not get correctly noticed by Rider. I dont get code highlighting and other helpers. It says: "Cannot resolve package "PACKAGENAME" with package version "GITHUB-REPO-LINK". Works fine in Unity though.

![image](https://user-images.githubusercontent.com/3932988/92718168-bf97df00-f361-11ea-9c07-9425f94e30e6.png)
![image](https://user-images.githubusercontent.com/3932988/92718190-c6beed00-f361-11ea-94f7-a8ef473704c2.png)

**Comment by van800** [comment] 2020-09-10 11:24
this is likely duplicate of https://youtrack.jetbrains.com/issue/RIDER-47191
fix would be public in RIder 2020.2.2 due this week.

**Closed by van800** 2020-09-10 11:24 UTC

**Comment by citizenmatt** [comment] 2020-09-10 11:42
Actually, that was part of Rider 2020.2, I don't know why YouTrack has that issue as released in 2020.2.2 - that version didn't exist when it says I set the Fixed In field 🤔 

Anyway, the fix is available in the latest version of Rider, currently 2020.2.1

**Comment by van800** [comment] 2020-09-10 11:44
BTW Rider 2020.2.2 was just released.
