### ISSUE TITLE
.csproj file sets LanguageVersion to 6

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#1193] opened 2019-05-17 19:24 UTC
The generated .csproj file sets LanguageVersion to 6, even though we use C# 7 features in our code.

This gives me errors when attempting to build the code using MSBuild (required as part of running code analysis using SonarQube).

I've located the code where this is set - _PerProjectSettings.InitLanguageLevelSettings_
There is a long comment inside this method explaining how the language version is calculated, but it appears that some of the justifications are very old (Unity 5.5) and i have not seen modern Unity versions taken into consideration (ones where C# 7 is supported out of the box without any external plugin or enabling "experimental" features).

When using VS, the language version property is set to "latest".

**Comment by van800** [comment] 2019-05-17 19:29
As a workaround you may override LangVersion to 7.3 instead of latest in Unity-Preferences-Rider.
However let us know more about the issue, specifically what Rider version, Unity version, Scripting Runtime are you using?

**Comment by tallior** [comment] 2019-05-18 09:42
Setting it via preferences works, BUT.... it's not the ideal solution as this setting is stored under EditorPrefs (local to my machine) and not shared among all devs on our team (via source control).

I could probably "patch" this with some editor code that is run as soon as Unity opens or something like that, and that makes sure that this setting is applied, but still would prefer a more stable and robust solution.

**Comment by van800** [comment] 2019-05-18 10:32
I totally agree we need a solid fix for the problem. First, let us know, how to reproduce it. Specifically what Rider version, Unity version, Scripting Runtime are you using?
We had somewhat similar issue fixed in 19.1 https://github.com/JetBrains/resharper-unity/issues/1043

**Comment by tallior** [comment] 2019-05-18 10:43
Oh, good to know something similar was fixed.

Unity = 2018.3.14
Rider = 2018.3.4
Scripting = .NET 4.6 equivalent

How to reproduce:

- Use the versions i mentioned above
- Make sure your project uses some C# 7 features
- from the command line build the .sln using msbuild:

msbuild /t:Rebuild MyGame.sln

(replace MyGame with the actual name of your solution).

The build fails with an error message (Since the .csproj file is not set to the correct language version).

**Comment by van800** [comment] 2019-05-18 10:45
Ok. since you are on Rider 2018.3.4, it makes total sense to try 2019.1.x. Could you please let us know, if this problem is fixed for your solution.

**Closed** 2019-05-19 14:28 UTC

**Comment by tallior** [comment] 2019-05-19 14:35
Why was this issue closed?

**Comment by van800** [comment] 2019-05-19 14:43
I closed it, because I think it was fixed in 19.1. However I am waiting for your response to prove it or not. Sorry for misunderstanding.

**Comment by tallior** [comment] 2019-05-19 14:55
regarding the upgrade - i am not sure whether as a team of around ~ 15 devs, can i upgrade Rider without affecting my team mates?

Rider creates (or rather adds) a .dll file to our Unity project. Can i safely add this DLL from 2019.1 when all my team members are on different versions ?

**Comment by van800** [comment] 2019-05-19 18:43
It would be nice of you to confirm if the issue is fixed in 19.1 or not. Trying it one time would not brake anything, unless you commit new EditorPlugin to vcs.

Regarding possible problems with upgrade. It may depend if you commit EditorPlugin to vcs or not. We do not recommend to commit EditorPlugin assembly to version control, you may once add it to .gitignore. Each dev locally would have his own EditorPlugin.

**Comment by tallior** [comment] 2019-05-20 07:14
I am going to verify it today and will post an update here.

**Comment by tallior** [comment] 2019-05-20 08:40
I just tested using Rider 2019.1.1, the LangVersion property in the generated .csproj files was set to "latest". Is this the expected behaviour after the bugfix?

BTW: i am not sure this happened because of the fix or because i previously applied the override in preferences (i tried removing it from EditorPrefs).

So, to sum up, as it appears, the issue is fixed with Rider 2019.1.1. thanks a lot !

**Comment by van800** [comment] 2019-05-20 09:06
Thank you for verifying it.
