### ISSUE TITLE
Attach to Unity Editor configuration from dll project

### ISSUE THREAD

**Issue by van800** [JetBrains/resharper-unity#1445] opened 2019-12-10 10:03 UTC
In Unity Dll project we have run-configuration Attach to Unity Editor.
Previously it worked in one click when one Unity instance was present.
Now it just shows error pop-up.
![image](https://user-images.githubusercontent.com/1482681/70519573-739edc00-1b3c-11ea-9d1b-bd43aae4ef1f.png)

**Comment by van800** [comment] 2019-12-10 10:22
Same behavior for regular Unity project when EditorInstance.json is missing for some reason.

**Comment by van800** [comment] 2019-12-11 08:04
@citizenmatt the plan is to restore attaching to single instance of opened Unity and show dialog if there is more than one. Do you agree?

**Comment by citizenmatt** [comment] 2019-12-11 09:02
The attach to single instance step was removed because it's essentially attaching to a random instance of Unity, and IMO it's better to show a dialog to confirm it's the right project in this case, and we shouldn't normally hit this scenario because either Unity or the plugin create `EditorInstance.json`. The main bug here is that showing the dialog has broken, probably because we've pushed checks to a separate thread.

How about this:

* Get list of editor processes
* Find the editor that matches the last attached process id, if it exists
* Else find the editor that matches `EditorInstance.json`, if it exists
* Else find the editor that matches the current project name, if it exists
* Show dialog for confirmation

There are circumstances on Windows (essentially not launched from Hub, with the `-projectPath` parameter) where we don't know an editor instance's project name, so we'd show the dialog. But the next time they hit debug, we've saved the pid, so it should match and attach without showing the dialog.

**Comment by Borluse** [comment] 2019-12-12 07:02
Is there any workaround currently? It's totally unusable for me because our whole scripts have been move out of Unity.

**Comment by van800** [comment] 2019-12-12 07:07
There is still Attach to Unity in the main menu.

**Comment by Borluse** [comment] 2019-12-12 07:18
![image](https://user-images.githubusercontent.com/317421/70690721-45fb9380-1cf2-11ea-8ac8-57934f6c0267.png)
not working, it can't found unity.

**Comment by Borluse** [comment] 2019-12-12 07:20
also, if i've attached to unity by rider 2019.2, then 2019.3 works perfectly, but not after restart unity.

**Comment by citizenmatt** [comment] 2019-12-12 08:49
@Borluse From the screenshot above - did you have Unity running at that time? If so, what's the name of the Unity process? We basically get the current list of processes and filter down by process name.

**Comment by Borluse** [comment] 2019-12-12 08:58
> @Borluse From the screenshot above - did you have Unity running at that time? If so, what's the name of the Unity process? We basically get the current list of processes and filter down by process name.

Yes, it is running. 
![image](https://user-images.githubusercontent.com/317421/70697355-51ee5200-1d00-11ea-9042-b55221eac0f9.png)
and task manager
![image](https://user-images.githubusercontent.com/317421/70697394-6599b880-1d00-11ea-9d11-7edaf6bfa9e3.png)
EditorInstance.json is correct
![image](https://user-images.githubusercontent.com/317421/70697478-89f59500-1d00-11ea-9aad-65e09cb8590f.png)

**Comment by van800** [comment] 2019-12-12 09:46
This issue might be caused by https://github.com/JetBrains/resharper-unity/issues/1454

**Comment by Borluse** [comment] 2019-12-12 10:24
> This issue might be caused by #1454
> I can reproduce it.

Exactly, i used to start my project from commandline. Tried starting unity directly, and it seems working. 
![image](https://user-images.githubusercontent.com/317421/70704260-a13a7f80-1d0c-11ea-9abf-71dfc02a4e31.png)

**Comment by citizenmatt** [comment] 2019-12-12 10:27
The problem is that the command line has a backslash followed by a quote, e.g. `Unity.exe "C:\Projects\SpaceGame\"`, and the code to extract the project name is treating the `\"` as an escape char, so instead of removing the quotes, it removes the `\` and leaves the quotes. This breaks path parsing, which causes an exception, which breaks the whole dialog.

Apologies for this, a fix is in progress as part of #1450, in the meantime, the workaround is to avoid the trailing slash in the command line, or even to use forward slashes, which is what Unity Hub does.

**Comment by Borluse** [comment] 2019-12-12 10:58
> The problem is that the command line has a backslash followed by a quote, e.g. `Unity.exe "C:\Projects\SpaceGame\"`, and the code to extract the project name is treating the `\"` as an escape char, so instead of removing the quotes, it removes the `\` and leaves the quotes. This breaks path parsing, which causes an exception, which breaks the whole dialog.
> 
> Apologies for this, a fix is in progress as part of #1450, in the meantime, the workaround is to avoid the trailing slash in the command line, or even to use forward slashes, which is what Unity Hub does.

Thanks! Changing commandline's project path from "d:\xx\xx" to "d:/xx/xx" works.

**Closed** 2019-12-16 12:45 UTC
