### ISSUE TITLE
Wrongly suggesting SerializedField is pointless on auto-property even when explicitely targeting the field

### ISSUE THREAD

**Issue by JeromeJ** [JetBrains/resharper-unity#1609] opened 2020-04-05 19:28 UTC
When using:

`[field: SerializedField] public string Foo { get; private set; }`

![image](https://user-images.githubusercontent.com/650065/78508217-5940dc00-7785-11ea-8c75-6014cc5b44b9.png)

Unity-Resharper wrongly implies the attribute is useless because properties can't be serialized by Unity. https://github.com/JetBrains/resharper-unity/wiki/Attribute-is-redundant-when-applied-to-this-declaration-type

But if specifically specifying the auto-generated back field using `field`, this actually works and it shouldn't suggest to remove the (not actually) useless attribute.

**Comment by citizenmatt** [comment] 2020-04-06 09:04
Duplicate of #1016

**Closed by citizenmatt** 2020-04-06 09:04 UTC
