### ISSUE TITLE
Rider window is not being focused when double clicking script file in Unity project view

### ISSUE THREAD

**Issue by Nufflee** [JetBrains/resharper-unity#252] opened 2017-10-19 21:19 UTC
This has been happening for a good while now. Basically when I double click a script file in project explorer or an log/warning/print message in console, Rider doesn't show up/focus. The file is actually open in Rider but I need to focus Rider myself. It is getting pretty annoying so I just wanted to address it here. I'm surprised that no one else is hitting this issue. It's been happening in multiple projects, even after reinstalling Windows/Rider/Unity a few times. I'm using Rider 2017.2

Cheers!

**Comment by van800** [comment] 2017-10-20 07:41
Here are couple of root causes:
1. Windows doesn't allow program to activate itself
2. Other option is SetForegroundWindow windows function, which has several limitations listed here
https://msdn.microsoft.com/en-us/library/windows/desktop/ms633539%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396
Main one for our case states that only if Rider was started by Unity it can be set foreground.

Could you please describe your workflow? Do you start Unity first and let it startup Rider?

**Comment by van800** [comment] 2017-10-20 07:43
I am closing this issue, but if you have any other ideas or if the described scenario is not working for you, I will still address it and reopen issue if needed. Thanks you for the feedback!

**Comment by Nufflee** [comment] 2017-10-20 11:57
Little update, from my testing it seems like it only happens when I let Unity open Rider. It works if I open Rider project before opening Unity.

**Comment by van800** [comment] 2017-10-20 12:03
@Nufflee Please switch Logging level to Verbose and paste here all the Unity Console output. Thanks!
![image](https://user-images.githubusercontent.com/1482681/31819978-613d0d2a-b59f-11e7-9b42-f3bace11db63.png)

**Comment by Nufflee** [comment] 2017-10-20 12:11
The part of Unity Editor log from when I double clicked the file https://pastebin.com/spVrPnpZ.

**Comment by van800** [comment] 2017-10-20 12:28
@Nufflee Before this log starts, was Rider started by Unity? Could you please make a full log starting with Unity startup, first double click causing Rider startup, second double click on different file, withexpected Rider window activation.

**Comment by Nufflee** [comment] 2017-10-20 12:37
Here: https://pastebin.com/xwAJQqZd @van800

**Comment by van800** [comment] 2017-10-20 13:41
Still can't see call for Rider.exe, which starts it.
[Rider] [Verbose] "C:\Program Files\JetBrains\Rider 2017.2\bin\rider64.exe" "C:\Work\resharper-unity-main\resharper\src\resharper-unity\Unity3dRider\Unity3dRider.sln" --line -1 "C:\Work\resharper-unity-main\resharper\src\resharper-unity\Unity3dRider\Assets/Plugins/Editor/JetBrains/RiderAssetPostprocessor.cs"
Can you confirm, that you did exactly the steps below?
1. double click causing Rider startup
wait startup, activate Unity window again
2. double click on different file

**Comment by van800** [comment] 2017-10-20 13:46
Is it Windows 10?

**Comment by Nufflee** [comment] 2017-10-20 14:03
Yes.

**Comment by van800** [comment] 2017-10-20 14:46
Unfortunately no idea for now. According to the logs SetForegroundWindow silently doesn't work.

**Comment by SugoiDev** [comment] 2017-10-20 18:09
Also have the problem (also on Windows 10).
It usually works, but then just stops for no particular reason. The icon on the Taskbar will flash, though.
I have the same issue using pinvoke in other scripts unrelated to Unity, so it might be some weirdness with Windows itself. I remember having similar issues with every Windows version since XP.

I still use my own Rider integration before this official one was available, and mine uses Autohotkey to force Rider to come to the front if it doesn't when I double click a script. The main reason I use my own is that I don't want to change the default editor in Unity so I can keep my assemblies named as when I use Visual Studio (for a number of reasons).

---

This doesn't apply here at all, but below is an (extreme) example of programs being nasty and not obeying Windows.
I had a particularly nasty bug once when trying to bring the Visual Studio to the front. It was a pretty deep rabbit hole until I reached some arcane knowledge to make the thread retry with a IOleMessageFilter and use the proper apartment for the entry point. Turns out that the window was busy (but didn't appear so) so it silently ignored Windows promoting it to front window.

**Comment by SugoiDev** [comment] 2017-10-20 18:11
Maybe an extra API in Rider so it can promote itself to front would be more consistent to using SetForegroundWindow from within Unity.

**Comment by van800** [comment] 2017-10-20 20:04
@SugoiDev On Windows there is no reliable legitimate way for an application to activate itself and "steal focus", I was thinking this way some time ago https://youtrack.jetbrains.com/issue/IDEA-172890

**Comment by SugoiDev** [comment] 2017-10-20 20:27
@van800 Interesting.

Here's the file with the code Autohotkey uses for this: https://github.com/AutoHotkey/AutoHotkey/blob/master/Source/window.cpp#L23
The juice is mostly here: https://github.com/AutoHotkey/AutoHotkey/blob/master/Source/window.cpp#L136

There's a lot going on there and many methods are tried in sequence (and also retries). It also deals with `LockSetForegroundWindow` that might have been set for some reason (like opening a menu or holding the ALT key).

Since this is so excessively complicated, it is probably out of scope of this project or even Rider itself. In the end, I just use Autohotkey directly and it does the job (usually). If even that fails, I give up.

**Comment by van800** [comment] 2017-10-20 21:16
@SugoiDev Also interesting! But unless there will be many complaints on current implementation, it doesn't feel right to include such hard-core hacks like AttachThreadInput.

**Comment by SugoiDev** [comment] 2017-10-20 22:27
@van800 Pretty much. I think that, even if there were a lot of complaints, it would probably be easier to compile a small helper program (could even be Autohotkey itself; no dependencies) than to bloat this extension with all this madness.

**Closed** 2017-11-06 21:25 UTC

**Comment by Lyrcaxis** [comment] 2018-05-03 12:18
help?

**Comment by SugoiDev** [comment] 2018-05-03 13:28
@Lyrcaxis I don't think there's any available fix for this.

Ensuring a window is the topmost window is a hard problem on Windows, and there's no trivial solution.

**Comment by artyom-zuev** [comment] 2018-05-28 07:37
But how are Visual Studio and MonoDevelop managing to accomplish that when being selected as preferred IDEs through Unity Editor preferences?

**Comment by van800** [comment] 2018-05-28 11:50
I added new fix for focus, it will appear in nightly builds in a couple of days.
https://github.com/JetBrains/resharper-unity/commit/8502766e9b070ab8d0fbf0e3b9dd1f3bf83a99e2

**Comment by van800** [comment] 2018-06-02 19:42
Latest fix is in 2018.1.2

**Comment by sorencoder** [comment] 2018-08-23 11:42
I still have this issue in Rider 2018.2 RC

**Comment by danielkrenn** [comment] 2018-11-12 01:42
Still seeing this issue in the latest version of Rider. Have you guys tried the following approach?

this.WindowState = FormWindowState.Minimized;
this.Show();
this.WindowState = FormWindowState.Normal;

**Comment by van800** [comment] 2018-11-12 08:12
@sorencoder @danielkrenn Are you on Windows?

**Comment by sorencoder** [comment] 2018-11-12 19:52
> @sorencoder @danielkrenn Are you on Windows?

Yes

**Comment by van800** [comment] 2018-11-13 07:45
@sorencoder Can you confirm that Rider process is started by Unity? (Otherwise Windows doesn't allow setting other application to front)

**Comment by Shpek** [comment] 2019-01-15 14:31
I have the same problem on Win 10. Starting from within or outside of Unity does not affect it. What does though is if you minimize Rider window from the taskbar button (you click the Rider icon in the taskbar while the Rider window has focus). After you do that it doesn't go to foreground when you open a file in Unity.
I have the same problem also when hitting breakpoints in the debugger. This one however is not affected by the window minimized status.
I have 2 monitors if this is of any help.

**Comment by sorencoder** [comment] 2019-01-29 13:04
> @sorencoder Can you confirm that Rider process is started by Unity? (Otherwise Windows doesn't allow setting other application to front)

I had to switch to Visual Studio. But the team is now using Rider  for our new project, and we have the this problem again.

We are developing online game. Server is also C# so I have two Rider instances open. One for client that gets started by Unity and one for server which is .Net Core console app.

If both Rider instances get minimized, Unity doesn't change focus to the Rider window. But if one of Rider instances remain open, everything works fine and the Rider instance for Unity pops up.

Hope it helps.

**Comment by victor647** [comment] 2019-04-12 10:05
Rider 2018.3.2 still have this problem >_<

**Comment by van800** [comment] 2019-04-12 10:37
@victor647 please try at lease 2018.3.4 or even 2019.1 EAP

**Comment by Virosa** [comment] 2019-08-11 21:22
This issue is happening for me with 2019.1.2

**Comment by mnarimani** [comment] 2019-08-11 21:32
@Virosa This issue was fixed somewhere in 2019.2 versions. Install the latest version and check if you have issues.

**Comment by Virosa** [comment] 2019-08-11 21:44
Does work so far on 2019.2, cheers.

**Comment by malexj93** [comment] 2020-09-29 19:50
I'm experiencing this issue with Rider 2020.2.3 and Unity 2019.4.11f1 on Windows 10. When opening a file from Unity with Rider not open, I get a prompt asking to open the file or the whole solution, and choosing either one properly opens Rider with focus. However, anytime I try to open another file from Unity after this, it doesn't get focus, it just opens in Rider and flashes orange in the taskbar. This also happens when I open Rider manually before clicking anything in Unity.

**Comment by van800** [comment] 2020-09-30 10:57
@malexj93 Try to install or update Rider package in Unity. Latest public version is 2.0.7.

**Comment by Kaiwoknats** [comment] 2025-07-31 20:43
I just came across this error and had it myself, using Rider 2025.1.1. I tried around tons of stuff until i found out that my rider was set to "Always start as admin". I think because my unity is not admin and tries to focus rider which is admin it doesnt work. I turned off my riders admin privs and now it works again. Hope this helps somebody.
