### ISSUE TITLE
Supress "field is never assigned"

### ISSUE THREAD

**Issue by ortin** [JetBrains/resharper-unity#37] opened 2016-06-03 15:42 UTC
Supress "field is never assigned" for public (and marked as [SerializeField]) fields in classed derived from MonoBehaviour

**Comment by citizenmatt** [comment] 2016-06-03 15:45
This is a duplicate of #15, which is fixed, but not yet released. I'll try and push a release next week.

**Closed by citizenmatt** 2016-06-03 15:45 UTC

**Comment by ortin** [comment] 2016-06-03 15:50
oh, sorry
didn't check closed ones

**Comment by citizenmatt** [comment] 2016-06-03 15:51
No problem :) It's not very obvious that a release is overdue...
