### ISSUE TITLE
Cache Processing takes forever

### ISSUE THREAD

**Issue by gekidoslair** [JetBrains/resharper-unity#2467] opened 2024-12-31 22:55 UTC
I have a large-ish Unity project and the 'Cache Processing' step when opening Rider takes literally an hour before Rider actually becomes useable. 

There has to be some way that you can save this cache or something so I don't have to do this every time I open rider
<img width="481" alt="2024-12-31 14_54_53-" src="https://github.com/user-attachments/assets/6e6580a5-2e5b-4fce-83a5-2e0602b4e246" />

**Comment by van800** [comment] 2024-12-31 23:23
Please reproduce this situation and call Help - Report a Bug, agree to attach logs. Thank you! I am closing this issue, since there is nothing we can do by just a screenshot.

**Closed by van800** 2024-12-31 23:23 UTC
