### ISSUE TITLE
Incorrect "Redundant Unity event function" warning

### ISSUE THREAD

**Issue by sorencoder** [JetBrains/resharper-unity#875] opened 2018-11-01 17:14 UTC
This should not generate any warning:
```
    public abstract class SealedSMB : StateMachineBehaviour
    {
        public sealed override void OnStateEnter(Animator animator, AnimatorStateInfo stateInfo, int layerIndex) { }

        public sealed override void OnStateUpdate(Animator animator, AnimatorStateInfo stateInfo, int layerIndex) { }

        public sealed override void OnStateExit(Animator animator, AnimatorStateInfo stateInfo, int layerIndex) { }
    }
````

But it generates warning for those three methods since they're sealing event functions.

Regards.

**Comment by citizenmatt** [comment] 2018-11-02 19:55
Duplicate of #794. This is already fixed in the [Rider 2018.3 EAP builds](https://www.jetbrains.com/rider/eap/).

**Closed by citizenmatt** 2018-11-02 19:55 UTC
