### ISSUE TITLE
Generic Unity event not initialised by Unity

### ISSUE THREAD

**Issue by iBicha** [JetBrains/resharper-unity#648] opened 2018-07-16 17:25 UTC
Consider:
```
[Serializable]
public class EventEx<T0> : UnityEvent<T0>
{
}
```
And then, a field on a mono behaviour:
```
public EventEx<string> MyEvent;
```

While Raider will tell you `This field is initialised by Unity`, it's actually not, because it's generic (as far as I can tell)

**Comment by citizenmatt** [comment] 2018-07-16 21:14
Duplicate of #505

**Closed by citizenmatt** 2018-07-16 21:14 UTC
