### ISSUE TITLE
Running Unity Unit Tests

### ISSUE THREAD

**Issue by brock555** [JetBrains/resharper-unity#70] opened 2016-11-21 21:10 UTC
I'm trying to see if I can run Unity3d unit tests from within Rider. Rider sees the tests, but when i try to run them I get this error "error: Target named 'Assembly-CSharp-Editor' not found in project. 

Also when I open up a Unity project it sees it as 3 projects (Assembly-CSharp, Assembly-CSharp-Editor, Assembly-CSharp-firstpass)

**Comment by citizenmatt** [comment] 2016-11-21 23:52
The three assembly projects are what Unity generates for a C# solution - I believe the same happens in Visual Studio Tools for Unity.

As for the tests, do you have any more details? I'm not familiar with testing in Unity, so links and (if possible) a repro would be brilliant.

Thanks!

**Comment by brock555** [comment] 2016-11-23 07:01
I've attached a new blank Unity project and the Unity Test Tools package, which includes example tests. For the tests to run within Unity they have to be in an Editor folder, but when I try running them in Rider I get the error I posted above.

[UnitTests.zip](https://github.com/JetBrains/resharper-unity/files/608242/UnitTests.zip)

**Comment by citizenmatt** [comment] 2016-11-23 22:17
Brilliant, thanks. How did you generate the solution and project files? Was it with the [Unity3dRider](https://github.com/JetBrains/Unity3dRider) plugin and the _Open C# project in Rider_ menu item? The issue is that the solution file has one name for the project, but another name for the project file. And Rider is trying to build using the project file names, rather than the project names.

I'll look into this a bit more, but I think I'll be raising an issue for Rider itself for this one.

**Comment by brock555** [comment] 2016-11-30 03:37
The solution and project files were generated using MonoDevelop

**Comment by citizenmatt** [comment] 2016-12-02 16:38
Thanks, it looks like Rider has problems getting the projects to build because the solution file uses a different name for the projects than the project file name, and even uses the same name for multiple projects! I'll follow up with the Rider dev team to see what we can do.

**Comment by citizenmatt** [comment] 2016-12-06 14:19
Looks like this is related to [RIDER-3288](https://youtrack.jetbrains.com/issue/RIDER-3288).

**Comment by igisav** [comment] 2017-06-22 08:25
I have the same error and it works only if Unity is open in background. Then you have ´Temp´ folder in project and tests run as expected.

**Comment by citizenmatt** [comment] 2017-06-22 08:41
Do you mean that you're seeing the `error: Target named 'Assembly-CSharp-Editor` message? And this error goes away if the `Temp` folder is there?

**Comment by igisav** [comment] 2017-06-22 09:48
Sorry, its my fault - I used wrong version of .Net framework (4.0.3) and the folder ´Temp/bin/Debug´ was empty.

With correct .NET version (4.7) everything is fine.

**Comment by van800** [comment] 2017-07-10 15:13
With plugin https://github.com/JetBrains/resharper-unity/tree/master/resharper/src/resharper-unity/Unity3dRider (which is automatically installed in most cases)
this problem is workarounded. For  the case without the plugin, I would still close this issue, since RIDER-3288 is opened. Please vote it.

**Closed by van800** 2017-07-10 15:13 UTC
Labels: rider-issue
