### ISSUE TITLE
Reference assembly action should update asmdef files

### ISSUE THREAD

**Issue by Baste-RainGames** [JetBrains/resharper-unity#852] opened 2018-10-19 10:51 UTC
Rider has a very convenient "Reference 'assembly' and use 'type'" quick-fix action when you're trying to use a type from a non-referenced assembly. That kicks in for types from other asmdef-generated assemblies, but since Unity uses the asmdef file's references to generate .csproj references, the asmdef file has to be updated by hand to make the code compile in Unity.

Ideally, the reference assembly action should update the asmdef file automatically. Is that doable?

**Comment by citizenmatt** [comment] 2018-10-29 13:34
This should be possible. If the reference being added is to another `.asmdef` based project, we should be able to do this, by implementing `IModuleReferencer`. This should allow us to check that the two modules can be referenced, and to do what needs to be done to make the reference happen. I suspect we'll need to modify the `.asmdef`, and also add the project reference, so that the type is immediately available and the quick fix completes successfully (after referencing the module, it needs to reference the type. If the module reference fails or doesn't fully complete, the type doesn't get referenced).

You can see somewhat out of date code for this in the [resharper-nuget project](https://github.com/JetBrains/resharper-nuget). It's circa ReSharper 8, and got rolled into the product for ReSharper 9. I don't think much has changed.

The outstanding question is that

**Comment by Baste-RainGames** [comment] 2018-10-31 10:39
For your first question: yes, there are - all of the ones from Unity's packages system. The rules for those are:
- you can reference them if they're mentioned in your project's Packages/manifest.json
- they do not have an asmdef file. Instead, their name is defined in AppData/Local/Unity/cache/packages/packages.unity.com/<package_name>@<package_version>/package.json
- the string defined in that package.json is the one used to name the assembly, and the one needed to insert into your assembly's manifest.json in order to reference that assembly.

This means that if you want to filter for assemblies that should be automatically added to an asmdef, you need to look though all other asmdef files in the project, and the manifest.json file of the project.

For your second question: seems like it. If I have a reference to assembly A in assembly B, Rider won't suggest that I add a reference to assembly B in assembly A. So that should be safe.

**Comment by citizenmatt** [comment] 2018-10-31 11:21
The first question is really determining if there is ever a scenario for trying to add a _purely binary reference_ to a `.asmdef` file. If so, we can't do anything in this case - a `.asmdef` file can only contain references to other `.asmdef` files.

What I mean by "purely binary reference" is an assembly that isn't part of a package, or isn't already referenced. Plugins and other .dll assets are already referenced, so we're good there. Source packages are `.asmdef` based, but ReSharper should be asking us to add a project reference, which we can use to easily find the `.asmdef` file to modify.

Cached packages are a little different. To ReSharper, they'll look like a simple binary file reference, but we need to know better. Cached packages are still `.asmdef` based - some packages contain multiple `.asmdef` files, compiling to multiple assemblies. The name in `package.json` is the name of the package, while the name of the assembly comes from the `.asmdef` file Unity used to compile it. So when we get a binary reference, we'll need to look it up in an index of `.asmdef` files. If we know it, we can modify the `.asmdef` file and add the binary assembly reference to the project (which Unity would also do as soon as the project files are regenerated). 

The problem is if the binary reference doesn't match a `.asmdef` file. We can't fix the `.asmdef` file in the source package here, and we need to know if we can ever get into this situation and how to handle it. This is the scenario that needs investigating - if this scenario is possible, where does that `.dll` come from?

The good news is that the assembly name is the same defined name in the `.asmdef` file (but not the filename!) and we already have an index of the `.asmdef` files in the C# solution. We need to extend this for various other things, and we'll be able to reuse it here, too.

I suspect that if we're modifying a `.asmdef` file inside a source package (i.e. it lives in `Packages` or is referenced with `file://` in `manifest.json`) then we might well need to add a package reference to `package.json` as well. And I'm not sure about a `.dll` asset that lives in `Assets` underneath a `.asmdef` file - I don't know how Unity will generate references here. These will both also need investigating.

**Comment by SugoiDev** [comment] 2018-10-31 13:40
In 2018.3+, there is something like a "purely binary reference" in asmdef files.
First, in the import settings of your compiled DLL, you can mark it as being "explicitly referenced". 

In the UI, this is being called "Auto Reference". You need to disable it for the assembly to marked as "explicitly referenced". Here's how it looks like
![screenshot 2018 10 31-10 10 44](https://user-images.githubusercontent.com/7355630/47791346-3e4c7b80-dcf8-11e8-8bf8-eb4896c2572f.png)

In the .meta file for that DLL, you'll have this

```
fileFormatVersion: 2
guid: cf2360dc86965534b80e461f9bc003ea
PluginImporter:
  (...)
  isExplicitlyReferenced: 1
  (...)
```

Now, you can use the "Assembly references" list in the asmdef import settings to add a reference to that 
DLL.

Here's how it looks like in the UI

![screenshot 2018 10 31-10 10 29](https://user-images.githubusercontent.com/7355630/47791382-5623ff80-dcf8-11e8-8c5c-1fbbb4a9bb0e.png)

and what the .asmdef file itself looks like

```
  (...)
    "overrideReferences": true,
    "precompiledReferences": [
        "TypeSafe.dll",
        "Enums.NET.dll",
  (...)
```

Note that the `overrideReferences` switch must be true for the `precompiledReferences` to be used.

DLLs with the "auto reference" switch disabled will not be added to any custom assembly unless you add them in the "assembly references" list.

I'm not sure about the "normal" Unity assemblies (non asmdef based). My guess is that the DLLs will still be referenced (since there's no way to configure the normal assemblies).

**Comment by citizenmatt** [comment] 2018-10-31 14:20
Awesome! That's brilliant to know. And I guess I need to update the [asmdef JSON schema](http://json.schemastore.org/asmdef), too!

**Comment by NoxMortem** [comment] 2019-01-10 19:38
Oh I would love if it would correctly update the asmdef :)

**Comment by Sroka** [comment] 2020-02-15 12:15
Any news on this?

**Comment by citizenmatt** [comment] 2020-08-17 14:07
We're currently planning Rider 2020.3, hopefully we'll include it then. See also [RIDER-48660](https://youtrack.jetbrains.com/issue/RIDER-48660)

**Comment by hybridherbst** [comment] 2020-11-22 21:50
@citizenmatt do you think this will make it to 2020.3? EAP8 doesn't seem to have it (yet). Fingers crossed 🤞

**Comment by citizenmatt** [comment] 2020-11-22 22:10
Sadly no. This hasn't made it for 2020.3, it's going to be 2021.1

**Comment by citizenmatt** [comment] 2021-01-14 10:15
Calling out an important detail that's easy to miss from above: consider also adding a package reference when adding an asmdef reference between two packages.

This is complicated with optional features, handled by version defines. These are symbols that are defined based on expressions that evaluate if a package is referenced, and what version of that package is referenced. They can be used to add optional features - support for a package wrapped inside defines. In this case, the `.asmdef` reference should be added, but the package reference is optional.

It doesn't appear to be possible to automatically decide if a package reference should be made. If a reference to a package that is already set up in version defines is required, then it might be an optional feature, or it might be version defines to allow handling multiple versions of the same package - it's still a required feature, but with optional behaviour. Similarly, an optional feature might add a reference to yet another package. It is unlikely that an optional feature should force a required reference, but it would be very hard to check that the consumer of the reference is an optional feature (optional feature or optional behaviour?). A simpler solution is to always prompt to add a package reference.

**Comment by marwie** [comment] 2021-07-22 10:09
> Sadly no. This hasn't made it for 2020.3, it's going to be 2021.1

Hey Matt, do you have any news on this?

**Comment by citizenmatt** [comment] 2021-08-03 13:01
No news, sorry. I'd like to get to this, but it's a larger piece of work that hasn't fitted in to date.

**Closed** 2022-02-14 20:55 UTC
Labels: enhancement

**Comment by lgarczyn** [comment] 2023-12-21 14:12
This feature only works sometimes. Most of the time, the error disappears, but the asmdef is not updated. As soon as I switch to Unity and back, the error re-appears.

**Comment by citizenmatt** [comment] 2023-12-21 14:21
@lgarczyn Yes, unfortunately, it's a bit buggy. We're hoping to address that in the next release, apologies for the inconvenience

**Comment by lgarczyn** [comment] 2023-12-21 14:38
> @lgarczyn Yes, unfortunately, it's a bit buggy. We're hoping to address that in the next release, apologies for the inconvenience

Thanks! It would be nice if the auto-fix also worked on "using" statements and extension methods, and not just missing types.

**Comment by citizenmatt** [comment] 2023-12-23 12:15
Not sure what you mean by that - can you give me an example, please?

**Comment by lgarczyn** [comment] 2023-12-23 13:05
> Not sure what you mean by that - can you give me an example, please?

If you are missing an assembly reference, 3 things might show errors. Missing types, unrecognized namespaces and missing extension methods.

Currently, rider only offers the "auto-fix" for missing types.
