### ISSUE TITLE
Add static analysis rule for detecting invalid usage of Unity APIs

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#1431] opened 2019-11-27 19:33 UTC
Most Unity APIs are only accessible from Unity's scripting thread.

This means that if you attempt to invoke them from any other thread, an exception will be thrown.

Field initializers for MonoBehaviour derived classes execute on a different thread (initialized internally by Unity), so any access to Unity APIs will result in an exception.

Example code:

```

using UnityEngine;

public class Test : MonoBehaviour
{
    public string msg = PlayerPrefs.GetString("key", "default");
}
```
Calling PlayerPrefs from that location will result in an exception.

Similarly, other using other Unity APIs will result in the same behaviour (i can probably come up with a more detailed list).

**Comment by krasnotsvetov** [comment] 2019-12-11 09:10
Hi!
Thank you for suggestions, if you have time to share your detailed list, please do it :) It will help us to cover more & more cases in our analysis

**Comment by tallior** [comment] 2019-12-11 15:33
Basically, i think that 99% of Unity's scripting APIs will not work in this way.
I don't think there's any guide that shows all of them, maybe i could create some sort of automated test that will check it. i will keep you posted.

**Comment by citizenmatt** [comment] 2019-12-16 22:45
Duplicate of #572

**Closed by citizenmatt** 2019-12-16 22:45 UTC
