### ISSUE TITLE
Fields marked with SerializeField produce Warning CS0649

### ISSUE THREAD

**Issue by iyakov** [JetBrains/resharper-unity#157] opened 2017-06-05 13:05 UTC
Hi, 

I've figured out that in VisualStudio fields marked with SerializeField produce Warning CS0649: Field '%field_name%' is never assigned to, and will always have its default value null. They also ignore [UsedImplicitly] attribute. Disabling this extension makes [UsedImplicitly] attribute to work as expected.

Extension version: 1.8.0 on 2017-06-05 12:53:17Z
Resharper version: 2017.1.20170428.80718 on 2017-04-28 08:07:28Z
Visual Studio version: 15.0.26430.12

Thanks,
Yahor

**Comment by nkAlex** [comment] 2017-06-05 13:55
Yeah, same thing in Visual Studio 2017 — all of the private serializable fields are underlined with a green line. This doesn't happen right after opening the project, but after some time of work (probably after compiling the code at least once, I haven't checked specifically).

**Comment by citizenmatt** [comment] 2017-06-05 13:57
Is this just an in-editor warning, or does it also appear in the Error List window? If it's in the Error List window, it's a warning from Visual Studio, rather than ReSharper.

**Comment by nkAlex** [comment] 2017-06-05 14:06
In build errors or in ReSharper's errors window?
I think it's maybe a VS2017 issue since it was working fine in VS2013 and looks more like a bug (can't seem to reproduce it right now, but it was definitely there yesterday). But shouldn't `[UsedImplicitly]` disable the warning anyway?

**Comment by citizenmatt** [comment] 2017-06-05 14:10
Visual Studio's own Error List window - View &rarr; Error List, if I remember correctly. Where compilation errors are displayed, and not in ReSharper's Solution Errors window.

`[UsedImplicitly]` is a ReSharper annotation, so will only suppress the ReSharper warning. If it's Visual Studio creating the warning, then it's not going to suppress it.

**Comment by iyakov** [comment] 2017-06-05 14:20
This happens after the compilation. The warning are displayed only in VisualStudio ErrorList window (not Resharper's one).
Note one more time, if I disable UnitySupport extension, the attribute [UsedImplicitly] works as expected.

**Comment by citizenmatt** [comment] 2017-06-05 14:21
Yes, I've just recreated this - it's Visual Studio itself doing this, when you build in VS. As far as I can tell, the only way to get rid of this is to either:

a) Use `#pragma warning disable 649`/`#pragma restore 649`
b) Don't build in VS - only build by switching to Unity
c) Tick the "Suppress Visual Studio squiggles" checkbox in ReSharper &rarr; Options &rarr; Code Inspection Settings.

**Comment by nkAlex** [comment] 2017-06-05 14:21
I think was a CodeLens suggestion, so, must be a VS warning. But I couldn't find a way to disable it.

**Comment by citizenmatt** [comment] 2017-06-05 14:26
I get the same behaviour without the R# Unity plugin installed - after build, the field is still marked with the warning, even if `[UsedImplicitly]` is applied to the field.

**Comment by iyakov** [comment] 2017-06-05 14:26
citizenmatt, yes, these walkarounds work, however
a) I have hundreds of files..
b) Building in VS is a convenient way to check and build the source code
c) hiding all inspections doesn't look a great idea..

In any case, thank you so much for your time!

**Comment by citizenmatt** [comment] 2017-06-05 15:27
Yeah, unfortunately, it's a VS warning, and there's not much we can do, so I'm going to close the issue. Feel free to reopen if you have any other thoughts or ideas.

Personally, I have R# disable the VS squiggles - R# will flag all compilation errors and warnings anyway, as well as its own analyses. And of course, I use the Unity plugin in Rider :)

**Closed by citizenmatt** 2017-06-05 15:27 UTC

**Comment by iyakov** [comment] 2017-06-06 10:47
I'm so sorry...

I just thought that R#'s [UsedImplicitly] attribute is designed exactly for suppressing this particular type of VS warnings (field is not used, field is not assigned, etc). 

I thought that if I enable this plugin the R#'s behaviour should not be changed (i.e. it suppresses these warnings with UnitySupport pugin disabled).

One more time, I'm so sorry I stole your time.
Best regards
