### ISSUE TITLE
Unity Monobehaviour auto-complete options show up but never actually complete. Undo also symptomatic during error.

### ISSUE THREAD

**Issue by petersrinivasan** [JetBrains/resharper-unity#595] opened 2018-06-14 20:31 UTC
When I begin typing Update, I expect Resharper code completion to give me an option for private void Update() { }. It DOES give me that option, but when I hit Enter, Return, Tab, click, or otherwise select the code completion option, it simply disappears, leaving "Upda" or "Awa" on the line I was typing.

This happens with at least all messages in Monobehaviour and ScriptableObject, including OnCollisionEnter and similar messages with more specific signatures.

All other code completion (normal class members and what-not) work fine. Switching to VS Intellisense allows me to geta working Unity message completion (I have the Resharper and VS Unity support extensions installed) but Ctrl+Alt+Space (bound to Resharper Intellisense) still just does nothing for messages.

I've also noticed that Undo seems to be pretty finicky, and I've read similar issues with Unity completion in earlier versions that also had an undo issue connected to them, maybe related to Live Templates.

Please find a gif showing the issue (Thanks to JetBrains for reproducing the bug and sending me a gif!)
![sstdjsozfp](https://user-images.githubusercontent.com/6565748/41436465-98ba3128-6fd6-11e8-9415-e40007f06c3c.gif)

**Comment by citizenmatt** [comment] 2018-06-15 07:03
Duplicate of #584

**Closed by citizenmatt** 2018-06-15 07:03 UTC
