### ISSUE TITLE
Availability in R# 2017.3.0

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#310] opened 2017-12-19 16:57 UTC
Hi
When will the plugin be released for 2017.3.0? 
I updated my test machine and it's not available under extensions.

Thanks,

**Comment by citizenmatt** [comment] 2017-12-19 16:58
Should be in the next day or two. Just need to do some testing.

Duplicate of #307

**Closed by citizenmatt** 2017-12-19 16:58 UTC

**Comment by rob8861** [comment] 2017-12-19 17:02
Thank you for the quick reply.

cheers,
