### ISSUE TITLE
Not Available in Separate Class Library Project

### ISSUE THREAD

**Issue by farzadmf** [JetBrains/resharper-unity#121] opened 2017-03-10 19:06 UTC
Hello,

Let me first thank you for the cool extension 👍 

Here's my problem: I have decided to create a separate class library project to be used in Unity (the DLL file is copied to the `Plugins` folder), but when I do `Alt + INS` to insert unity functions, the option for **Unity Event Functions** is disabled

**Comment by CAD97** [comment] 2017-03-10 19:38
Just checking: your external project has view of the UnityEngine DLL and your class is extending `MonoBehaviour`?

**Comment by farzadmf** [comment] 2017-03-11 00:45
I'm not exactly sure what you mean by "view of the DLL", but I have added the reference in my project to `UnityEngine.dll`, and yes, my class is extending `MonoBehaviour`

**Comment by farzadmf** [comment] 2017-03-14 14:11
No one to help here? :(

**Comment by citizenmatt** [comment] 2017-03-14 14:14
If your class is deriving from `MonoBehaviour`, can you add a public field and see if it gets the little Unity icon? You can only add event functions if the text cursor is inside a class that derives from `MonoBehaviour`, or similar class.

Is everything working as expected in a standard Unity project?

**Comment by farzadmf** [comment] 2017-03-14 14:25
This is a screenshot from a "normal" unity project:
![image](https://cloud.githubusercontent.com/assets/5768792/23905026/317436b0-08a0-11e7-8407-0ffd5fc32874.png)

And this is a screenshot from my class library project:
![image](https://cloud.githubusercontent.com/assets/5768792/23905030/3500d806-08a0-11e7-9c16-08a755675c3f.png)

As you can see, the unity icons are being displayed, but the `Unity Event Functions` option is disabled when I do `Alt + INS`. One difference is that my class library is inside a `namespace`, but I tried bringing the class out of the `namespace`, but still the option is disabled

**Comment by citizenmatt** [comment] 2017-03-15 18:57
Ah! I've managed to recreate this. The issue is that the plugin has no idea what version of Unity you're building against, so doesn't know what API set to use, and so doesn't offer any methods that you can create.

Right now, I'm not sure how to fix this. Currently, I get the version of Unity to target by looking at the defines that Unity normally creates, looking for something like `UNITY_5_5` (if you add this, you'll get the generation functionality back). I don't know a better way of doing this - the UnityEngine.dll assembly has a version of 0.0.0.0, so I can't look there.

What kind of solution do you have here? Is it a completely standalone solution that you then copy the assemblies into the Assets folder of a Unity project? Does this code live in the same file structure as the Unity project? Anywhere near a ProjectSettings folder, for example?

**Comment by farzadmf** [comment] 2017-03-15 20:08
This is a solution created at the same level as the `Assets` folder (not inside of it); this is to prevent Unity from trying to compile the C# scripts I create. For this reason, yes, the solution for this folder can be considered a sibling of `ProjectSettings`.

Furthermore, I have configured the project's build directory to be `Assets/Plugins` (more specifically `..\Assets\Plugins`) so that every time I build the project, the DLL file is copied to that directory and Unity sees it

**Comment by citizenmatt** [comment] 2017-03-15 21:39
You're not the first person I've met to work like this, though - have a second solution that contains a lot of Unity code that lives outside of the Unity asset DB, then add it to the editor as a reference. I'd like a more intuitive way of handling this.

Can anyone else watching this thread jump in with some comments? Is this a non-traditional way of doing things, or are more people working like this?

**Comment by nkAlex** [comment] 2017-03-15 21:49
Pretty sure there are many people doing this.
And there are a lot of assets on the Asset store which include code inside of pre-compiled dlls, all those people must be compiling them somehow ;)

**Comment by CAD97** [comment] 2017-03-15 22:14
Here's a recent video describing a out-of-Unity setup (specifically in the context of enabling C#7 features that can run on the Unity run-time, but that doesn't matter too much): https://youtu.be/pJPtlEDIemw

I think that the ideal way for the plugin to handle this would be something like this:

- If Unity `#define`s exist, use those (current behavior)
- If the project _is not_ linked to the UnityEngine DLL, leave it alone
- If the project _is_ linked to the UnityEngine DLL
  - If the plugin can find `<Unity Project>/ProjectSettings/ProjectVersion.txt`, use the `m_EditorVersion` string from that
  - else, prompt the user and provide an easy way to specify which version of Unity they're building agianst, and create the custom `#define` automatically.

@farzadmf, is it possible to add additional projects to the unity-generated `.sln` without Unity destroying them? If you're putting the project folder alongside it already, as is the `Assets` "project", I think that would be the best workflow (though I haven't ever done so).

**Comment by farzadmf** [comment] 2017-03-16 04:45
@CAD97 Thank you for your answer. Actually, another video from the same guy on YouTube was the reason I tried using a separate class library for my scripts :)

I'm not sure what you mean by adding additional projects to the Unity-generated solution.

I put my VS solution in project's root folder (as a sibling of `Assets`) to make sure Unity doesn't try to compile the scripts inside of my solution

And now that I've used this approach, I don't think I'm gonna go back to using scripts directly; this is much more convenient (especially with @citizenmatt tip about the `DefineConstants` to make the ReSharper extension work correctly)

**Comment by sarbian** [comment] 2017-04-04 17:27
I would like to add my support for this. I create mods for a Unity game so all my project are library project that lives outside any Unity project dirs. 
I will have a look at adding the DefineConstants trick. Maybe adding a way to do that with simple menu would be enough.

**Comment by citizenmatt** [comment] 2018-04-06 09:54
I'm closing this in favour of #504

**Closed by citizenmatt** 2018-04-06 09:54 UTC
