### ISSUE TITLE
Referencing another assembly would modify the asmdef

### ISSUE THREAD

**Issue by sebas77** [JetBrains/resharper-unity#1343] opened 2019-10-03 16:00 UTC
I will throw it out there, but it would be mega awesome if every time Rider recognises that a type is referenced by another assembly would also modify the current unity asmdef to include that assembly (if possible) as I end up doing it manually every time

**Comment by citizenmatt** [comment] 2019-10-07 16:31
Duplicate of #852

**Closed by citizenmatt** 2019-10-07 16:31 UTC
