### ISSUE TITLE
GetDefaultApp throws an exception

### ISSUE THREAD

**Issue by tallior** [JetBrains/resharper-unity#359] opened 2018-02-13 16:50 UTC
This happens when we run Unity in batch mode (command line) on our build server.
Here's the exception that is thrown:
```
ArgumentException: An empty file name is not valid.
  at System.IO.FileSystemInfo.CheckPath (System.String path) [0x0001c] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileSystemInfo.cs:255 
  at System.IO.FileInfo..ctor (System.String fileName) [0x00017] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.IO/FileInfo.cs:58 
  at (wrapper remoting-invoke-with-check) System.IO.FileInfo:.ctor (string)
  at Plugins.Editor.JetBrains.RiderPlugin.GetDefaultApp () [0x00033] in C:\TeamCity\buildAgent\work\Build_ios_Unity_2017_1_1\Assets\Editor\JetBrains\Unity3DRider.cs:496 
  at Plugins.Editor.JetBrains.RiderPlugin..cctor () [0x00001] in C:\TeamCity\buildAgent\work\Build_ios_Unity_2017_1_1\Assets\Editor\JetBrains\Unity3DRider.cs:655 
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for Plugins.Editor.JetBrains.RiderPlugin
  at (wrapper managed-to-native) System.Runtime.CompilerServices.RuntimeHelpers:RunClassConstructor (intptr)
  at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) [0x00026] in /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101 
```

**Comment by citizenmatt** [comment] 2018-02-13 16:55
Duplicate of #320, should be available in Rider 2017.3.1, please update.

**Closed by citizenmatt** 2018-02-13 16:55 UTC
