### ISSUE TITLE
Incorrect C# version detection for Unity cs projects

### ISSUE THREAD

**Issue by XtroTheArctic** [JetBrains/resharper-unity#980] opened 2019-01-05 01:10 UTC
Hello.

A while ago, I had a similar problem and I got it resolved after reporting it in here: https://github.com/JetBrains/resharper-unity/issues/150

This time, the problem is the other way around.

C# version detection is correct for VS DLL projects but it's wrong for projects generated by Unity.

Resharper C# version detection used to produce "default" value for Unity generated projects in the past. I don't know when it got broken but currently it produces C# 6 which is incorrect because Unity now supports newer versions such as 7.0 and 7.1+.

For example:
Unity can compile this code without a problem but Resharper Unity plugin shows an error because it thinks it's a C# 7 feature and not supported by Unity.

Can you please fix this?

![adsiz](https://user-images.githubusercontent.com/6631429/50718350-a0509680-1043-11e9-9056-aba636faab93.png)

**Comment by van800** [comment] 2019-01-05 09:03
For VS we do not affect and we can't affect generated C# LangLevel.

**Comment by XtroTheArctic** [comment] 2019-01-05 12:35
I think there is a misunderstanding. I am not talking about a generated code. I am talking about Resharper's C# level property.

This property is not a regular VS project property. It's added by Resharper. It goes away when I suspend Resharper.

Have you seen this link I provided for the old (and fixed) bug?
This one is similar to the old one but in the other way around.
https://github.com/JetBrains/resharper-unity/issues/150

@citizenmatt Anything to say?

**Comment by van800** [comment] 2019-01-06 16:17
Could you please check the LangVersion in csproj?

**Comment by XtroTheArctic** [comment] 2019-01-06 17:46
<LangVersion>latest</LangVersion>

**Comment by XtroTheArctic** [comment] 2019-01-06 17:47
I told you that the problem goes away when I suspend Resharper. This is a Resharper Unity plugin bug.

**Comment by StephenHodgson** [comment] 2019-01-06 17:52
I've also noticed this bug as well

**Comment by van800** [comment] 2019-01-14 21:23
I expect this is fixed in 2018.3, just wait for https://github.com/JetBrains/resharper-unity/issues/853
Sorry for delay.

**Closed** 2019-01-14 21:23 UTC

**Comment by Lordfirespeed** [comment] 2024-04-21 09:31
I think some kind of regession may have occurred; I am experiencing this issue in Rider 2024.1.

**Comment by van800** [comment] 2024-04-21 09:43
@Lordfirespeed why do you want latest? I imagine with newest build tool specified in the Rider settings it may lead to suggestions of code, which would not compile in Unity.

**Comment by Lordfirespeed** [comment] 2024-04-21 10:05
I don't need it to compile in Unity, I compile it using the `dotnet` CLI and use [Doorstop](https://github.com/NeighTools/UnityDoorstop) to invoke my entrypoint.

But that's not relevant whatsoever! If the project **explicitly says** 'Use latest `LangVer`', that shouldn't be overridden. 
Plus, the behaviour being different on Linux to Windows points to a bug.

**Comment by van800** [comment] 2024-04-21 10:35
Since your setup is not a regular Unity one, would you please create a new report with Help - Report a bug, agree to attach logs? Please attach a solution for us to reproduce.

I think, you might have different build tool version specified in Linux and Windows.
