### ISSUE TITLE
Unused private fields are not flagged as "unused"

### ISSUE THREAD

**Issue by rob8861** [JetBrains/resharper-unity#587] opened 2018-06-07 19:33 UTC
Hello,

I recently noticed that unused private fields no longer get flagged as being "unused" (getting dimmed).
However, if I decorate the field with [SerializedField] then they will be flagged as "unused" if they are truly not being used in the code.

For example

```
public SomeClass : MonoBehavious 
{

         private float _x;  // will not be flagged as "unused"

         [SerilaizedField]
         private float _y; // will be flagged as "unused"

         // both _x and _y are not being used in the class
}
```

NOTE:   A non-Unity project does not exhibit this issue.

**Comment by citizenmatt** [comment] 2018-06-08 10:00
This is actually expected behaviour. Unity disables warnings for the [CS0169 compiler warning](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0169), which warns when a class member, such as a field, is unused. Rider (and the underlying ReSharper engine) respect this setting, and so doesn't show warnings for unused private fields. I don't believe anything has changed in the Rider/ReSharper behaviour here, so I'm going to close this with the dreaded "by design".

**Closed by citizenmatt** 2018-06-08 10:00 UTC

**Comment by oxysoft** [comment] 2019-05-28 16:30
Hi, is it be possible to know why? I've been wondering for a while why Rider doesn't warn me of unused members. Unless there is an important reason why, it should be possible to override this setting.

**Comment by citizenmatt** [comment] 2019-07-15 18:15
Unity disable the warning to simplify working with serialised fields. It's possible to have a private field be a serialised field if you use the `[SerializeField]` attribute. In this case, the field isn't initialised by code, so the compiler should show a warning. However, it is initialised by Unity, so the warning is redundant.

**Comment by bartlomiej-dawidow** [comment] 2020-02-07 15:43
It'd be great if resharper-unity had an option to override that behavior and only ignored the warning if it's annotated with `[SerializeField]`.

**Comment by van800** [comment] 2020-02-07 15:54
@bartlomiej-dawidow Please follow this request https://youtrack.jetbrains.com/issue/RIDER-38826 about it.

**Comment by van800** [comment] 2024-05-28 09:48
@benblo The behaviour with not greyed out private fields is not specific to Unity project, please ask with Help->Report a Bug or Help->Contact Support.

**Comment by benblo** [comment] 2024-06-12 13:09
> @benblo The behaviour with not greyed out private fields is not specific to Unity project, please ask with Help->Report a Bug or Help->Contact Support.

Thanks, I finally took the time to report it there: https://youtrack.jetbrains.com/issue/RIDER-113399/Unused-private-fields-are-not-flagged-as-unused
