### ISSUE TITLE
"Could not evaluate the value" after upgrade to Rider 2018.3

### ISSUE THREAD

**Issue by Borluse** [JetBrains/resharper-unity#972] opened 2018-12-21 09:31 UTC
Sorry for english.
After upgrade to 2018.3, i got "could not evaluate the value" message when debug with Unity. The debug panel displays correctly the variables. 

Win 10 1809, unity 2017.4 .

Thanks

**Comment by citizenmatt** [comment] 2018-12-29 21:06
There have been a number of fixes around the debugger in [Rider 2018.3.1, released on 27th December](https://blog.jetbrains.com/dotnet/2018/12/27/rider-2018-3-1-bug-fix-update/). Please could you update and try again?

I'm closing the issue for now, feel free to open again if the problem isn't fixed.

**Comment by Borluse** [comment] 2018-12-30 09:36
2018.3.1 still not working, have contacted with jetbrains.

**Comment by MWAudioAI** [comment] 2019-01-09 09:22
2018.3.1 still having this issue. Happens with both Unity 2018.2 and 2018.3

**Comment by Borluse** [comment] 2019-01-10 01:34
@MWAudioAI there's a youtrack about this. https://youtrack.jetbrains.com/issue/RIDER-22816. They gave a link of EAP version in the comment, you may want to take a look and give a try.

**Comment by AlexWhaley** [comment] 2019-01-10 12:23
I'd like to add that 2018.3.1 is still not working with the current enterprise versions of unity 2017.4.1f1 - 2017.4.17f1

**Comment by van800** [comment] 2019-02-19 15:21
Is expected to be fixed in https://youtrack.jetbrains.com/issue/RIDER-22816
In case it is still there, please follow up in youtrack.
Debugging is Rider core functionality it has an established process YT.

**Closed by van800** 2019-02-19 15:21 UTC
