### ISSUE TITLE
Jetbrains tells me that null comparison is only expensive when adding (variable == null) and not just (variable) ?

### ISSUE THREAD

**Issue by janimator0** [JetBrains/resharper-unity#1859] opened 2020-09-24 10:57 UTC
I know that using null checks can be expensive. The main reason I found out about this is that JetBrains Rider IDE marks (gameObject == null) as expensive when placed in an Update method. While it does this, it doesn't seem to mark these two alternatives to null checks as expensive. I would like to know if the below null checks are actually not expensive or just an oversight from the IDE?

```
if( gameObject == null ){}  // Marked as an expensive null check
 
if( gameObject ){}  // Not marked as an expensive null check
if( ReferenceEquals( gameObject, null ) ){}  // Not marked as an expensive null check
```

**Comment by citizenmatt** [comment] 2020-10-29 17:23
See also #1805

**Comment by citizenmatt** [comment] 2020-10-31 12:19
Duplicate of #1494

**Closed by citizenmatt** 2020-10-31 12:19 UTC
