### ISSUE TITLE
Rider causes Unity 5.6.x crash: Assertion at ..\mono\mini\method-to-ir.c:10721, condition `ins->opcode >= MONO_CEE_LAST' not met

### ISSUE THREAD

**Issue by Arakade** [JetBrains/resharper-unity#660] opened 2018-07-24 21:14 UTC
Rider beta seems to crash Unity 5.6.0 and 5.6.6 (I updated to see if it fixed).
Problem seems to exhibit with 182.3894.32 (I updated from 182.3797.69 to see if it fixed).
Problem happens as soon as `JetBrains.Rider.Unity.Editor.Plugin.Repacked.dll` is added.
Unity log simply shows last line of:

```
* Assertion at ..\mono\mini\method-to-ir.c:10721, condition `ins->opcode >= MONO_CEE_LAST' not met
```

Restarting will see Unity crash again with the same error.
Problem can be worked-around by deleting the dll and ensuring Rider doesn't replace it.

Problem doesn't seem to happen with Unity 2018.2 (when last I checked a couple of weeks ago).

**Comment by van800** [comment] 2018-07-25 02:56
Thanks for the heads up.
This must be  https://issuetracker.unity3d.com/issues/dot-net3-dot-5-editor-crashes-from-a-fixed-statement-in-unsafe-dll-compiled-by-vs2017

**Comment by van800** [comment] 2018-07-25 03:17
Fix would require using old VS like 15.1 at our build machine instead of new one.

**Comment by o2deprived** [comment] 2018-07-27 19:42
Also works in 2017.4, but not 2017.3. Just confirmed crash in 5.6.4 as well with (182.3894.140 Rider plugin v2018.2.0.20). Is the solution to roll back to Rider 2018.1? Any way to roll the plugin back?

**Comment by Arakade** [comment] 2018-07-30 11:19
Given this is fixed in Unity 2018.2, might Rider handle 5.6?  Perhaps detect older Unity and use an older plugin?

**Comment by van800** [comment] 2018-07-30 12:21
@Arakade Yes, fix for 5.6 is in process.

**Comment by van800** [comment] 2018-08-01 08:11
Fix landed in the Nightly builds. Tested in Unity 5.6.6. Nightly builds are available via https://www.jetbrains.com/toolbox/app/

**Closed by van800** 2018-08-01 08:11 UTC

**Comment by Arakade** [comment] 2018-08-01 11:15
Great.  Works.  Thanks!
I see this error when I first start Rider (with Unity previously running so only doing the new DLL).
It doesn't seem to cause any problem but thought I'd mention.  It's in my full project so obviously it _could_ be a bad interaction with other stuff.

[Rider-new-dll-innocuous-error.txt](https://github.com/JetBrains/resharper-unity/files/2249199/Rider-new-dll-innocuous-error.txt)

**Comment by van800** [comment] 2018-08-01 11:49
I saw that in Unity 5.6.3, but then updated to 5.6.6f2 and it disappeared. But I see that you have it 5.6.6, thanks for mentioning.

**Comment by Arakade** [comment] 2018-08-02 12:26
Yes that's right, mine is 5.6.6f2.
I also note that when I press "Pause" (or unpause) in Unity Editor, I now get this error (in Unity Log):

```
AssertionException: !IsLocalChange: RdProperty<bool>: `UnityEditorPlugin.EditorPluginModel.pause`
  at JetBrains.Util.Assertion.Fail (System.String message) [0x00000] in <filename unknown>:0 
  at JetBrains.Util.Assertion.Fail (System.String message, System.Object arg) [0x00000] in <filename unknown>:0 
  at JetBrains.Util.Assertion.Assert[RdReactiveBase] (Boolean condition, System.String message, JetBrains.Platform.RdFramework.Base.RdReactiveBase arg) [0x00000] in <filename unknown>:0 
  at JetBrains.Platform.RdFramework.Base.RdReactiveBase.UsingLocalChange () [0x00000] in <filename unknown>:0 
  at JetBrains.Platform.RdFramework.Impl.RdProperty`1[System.Boolean].set_Value (Boolean value) [0x00000] in <filename unknown>:0 
  at JetBrains.Platform.RdFramework.Base.RdReactiveEx.SetValue[Boolean] (IRdProperty`1 p, Boolean value) [0x00000] in <filename unknown>:0 
  at JetBrains.Rider.Unity.Editor.PluginEntryPoint+<>c__DisplayClass25_0.<AdviseUnityActions>b__1 () [0x00000] in <filename unknown>:0 
  at JetBrains.Rider.Unity.Editor.MainThreadDispatcher.Queue (System.Action action) [0x00000] in <filename unknown>:0 
  at JetBrains.Rider.Unity.Editor.PluginEntryPoint+<>c__DisplayClass25_0.<AdviseUnityActions>b__0 () [0x00000] in <filename unknown>:0 
  at JetBrains.Rider.Unity.Editor.PluginEntryPoint+<>c__DisplayClass25_0.<AdviseUnityActions>b__8 () [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) UnityEditor.EditorApplication/CallbackFunction:invoke_void__this__ ()
  at (wrapper delegate-invoke) UnityEditor.EditorApplication/CallbackFunction:invoke_void__this__ ()
  at UnityEditor.EditorApplication.Internal_PlaymodeStateChanged () [0x00010] in C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:335 
UnityEditor.EditorApplication:set_isPaused(Boolean)
JetBrains.Rider.Unity.Editor.<>c__DisplayClass25_2:<AdviseUnityActions>b__5()
JetBrains.Rider.Unity.Editor.MainThreadDispatcher:Queue(Action)
JetBrains.Rider.Unity.Editor.<>c:<AdviseUnityActions>b__25_4(Boolean)
JetBrains.Platform.RdFramework.Util.Signal`1:Fire0(Action`1[], Boolean)
JetBrains.Platform.RdFramework.Util.Signal`1:Fire(Boolean)
JetBrains.Platform.RdFramework.Util.RProperty`1:set_Value(Boolean)
JetBrains.Platform.RdFramework.Impl.RdProperty`1:set_Value(Boolean)
JetBrains.Platform.RdFramework.Base.RdReactiveEx:SetValue(IRdProperty`1, Boolean)
JetBrains.Rider.Unity.Editor.<>c__DisplayClass25_0:<AdviseUnityActions>b__1()
JetBrains.Rider.Unity.Editor.MainThreadDispatcher:Queue(Action)
JetBrains.Rider.Unity.Editor.<>c__DisplayClass25_0:<AdviseUnityActions>b__0()
JetBrains.Rider.Unity.Editor.<>c__DisplayClass25_0:<AdviseUnityActions>b__8()
UnityEditor.EditorApplication:Internal_PlaymodeStateChanged() (at C:\buildslave\unity\build\artifacts\generated\common\editor\EditorApplicationBindings.gen.cs:335)
UnityEditor.EditorApplication:set_isPaused(Boolean)
UnityEditor.Toolbar:DoPlayButtons(Boolean) (at C:\buildslave\unity\build\Editor\Mono\GUI\Toolbar.cs:507)
UnityEditor.Toolbar:OnGUI() (at C:\buildslave\unity\build\Editor\Mono\GUI\Toolbar.cs:345)
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/editor/EditorApplicationBindings.gen.cs Line: 335)

```

**Comment by van800** [comment] 2018-08-03 05:51
Hmm, I can't reproduce it. Does it reproduce for you on any project or just yours? Thanks!

**Comment by Arakade** [comment] 2018-08-03 08:42
_(Msg received.  Will check next week.)_

**Comment by van800** [comment] 2018-08-13 10:05
@Arakade any update on last issue? Thanks!
