### ISSUE TITLE
Extend encapsulate field with an option to mark the backing field as `SerializeField`

### ISSUE THREAD

**Issue by JurjenBiewenga** [JetBrains/resharper-unity#1883] opened 2020-10-08 07:13 UTC
This should most likely also be the default option if the field is in a `Serializable` class (in a Unity project), or at least when the class derives from a Unity class.

Should also check whether the field type is serializable.

**Comment by citizenmatt** [comment] 2020-10-29 17:18
Duplicate of #55

**Closed by citizenmatt** 2020-10-29 17:18 UTC
