### ISSUE TITLE
Game stops on breakpoint in Rider but in Unity Editor game continues playing. 

### ISSUE THREAD

**Issue by oddmax** [JetBrains/resharper-unity#714] opened 2018-08-15 14:14 UTC
Hello!

I have an issue in Rider debugging.
I connect a debugger, put some breakpoint in a method which executes in the main thread. After that Rider shows me that breakpoint worked, I can see a stack trace and some variables values, but meanwhile, the game actually continues running in Unity editor. And if I press 'Step over' or anything else it looks likes if I would have pressed 'Continue'.

[mono-sgen_2018-08-15__16-06-22.log](https://github.com/JetBrains/resharper-unity/files/2290472/mono-sgen_2018-08-15__16-06-22.log)

**Comment by oddmax** [comment] 2018-08-15 14:30
Rider 2018.1.4
Unity 2017.1.3p3
Scripting Runtime version: .NET 3.5 Equivalent
API Compatibility Level: .NET 2.0 Subset

**Comment by van800** [comment] 2018-08-15 18:57
@oddmax We are about to release Rider 2018.2 including may debugger fixes.
Could you give it a try? Either from here https://www.jetbrains.com/rider/eap/ or via https://www.jetbrains.com/toolbox/app/ which helps maintaining several versions simultaneously.

**Comment by oddmax** [comment] 2018-08-16 13:27
Tried 2018.2 EAP built August 10, the issue is still present. And disabling 'Enable external source debugging' option doesn't help.

**Comment by Iliya-usov** [comment] 2018-08-16 13:56
@oddmax Hello!
Can you provide us with your solution?
Or reproduce this problem on a simple solution?

**Comment by oddmax** [comment] 2018-08-16 14:13
Unfortunately, I'm not allowed because of NDA, but I will try to reproduce it in a simple solution (not sure how though).

**Comment by Alloc86** [comment] 2018-08-24 12:42
Just found this while looking for something else ... While I can neither provide a project (> 20 GiB by now ;) ) nor do I know in what situations exactly it fails I can confirm that this issue occurs every now and then. It *feels* like it's specific things that trigger it, i.e. breakpoints in such specific places always fail, while other breakpoints will always work.

**Comment by van800** [comment] 2018-08-24 21:43
At least add a screenshot, when it happens, we may guess some pattern and reproduce it then.

**Comment by van800** [comment] 2018-09-27 13:54
@oddmax , @Alloc86 Does this problem reproduce only inside coroutines?

**Comment by Alloc86** [comment] 2018-09-27 16:03
@van800 Sorry, didn't yet experience this again since I posted the message. I'm relatively confident though that at least on some instances it was *not* within a coroutine. Will definitely make sure to get back whenever I get this again and with more information in those cases :)

**Comment by van800** [comment] 2019-02-20 09:00
Debugging is a core Rider feature, so we can't really address much of its issues in this plugin scope. So I am closing this issue here. However if it still reproduces, please post an issue in https://youtrack.jetbrains.com/issues/RIDER

**Closed by van800** 2019-02-20 09:00 UTC
