### ISSUE TITLE
 "Field can be made readonly" code inspection for fields with SerializeField attribute

### ISSUE THREAD

**Issue by artem-sukhliak** [JetBrains/resharper-unity#644] opened 2018-07-12 15:05 UTC
In my code I have a field with SerializeField attribute. Rider suggests to mark that field with readonly, cause in my code value changes only in constructor. If I do that field becomes non serializable. My suggestion is to don't suggest such fields as readonly in general.

For example:

`
public class Foo : MonoBehaviour
{
    [SerializeField] private Position_pos;

    [Serializable] public struct Position
    {
        [SerializeField] private Vector2Int _point1; // suggest here

        public Position(Vector2Int point1)
        {
            _point1 = point1;
        }
    }
}
`

Unity 2017.2.1f1
JetBrains Rider 2018.1.3 (Build #RD-181.4952.311, built on June 27, 2018)

**Comment by citizenmatt** [comment] 2018-07-12 15:40
Duplicate of #419 

This will be fixed in Rider 2018.2. The [Early Access Preview program has started](https://www.jetbrains.com/rider/eap/), and it'll be in the EAP3 build.

**Closed by citizenmatt** 2018-07-12 15:40 UTC
